# Definitions part 2: rows 292-445
DEFS = {}

DEFS[292] = "Modules are not explicitly defined; the paper identifies a multienzyme complex in living cells in which glycolytic enzymes physically assemble into a metabolon. This metabolic module — a protein complex of sequentially acting glycolytic enzymes — channels metabolic flux through substrate channelling. The module is defined by direct protein-protein interactions, co-localisation in living cells, and functional cooperativity in glucose catabolism."

DEFS[293] = "Modules are not explicitly defined; the paper reviews the human de novo purine biosynthesis pathway. The ten-enzyme de novo purine synthesis pathway constitutes a functional metabolic module whose enzymes are co-regulated and have been proposed to assemble into a multi-enzyme complex (the purinosome). The module is defined by sequential enzymatic catalysis producing IMP from simple precursors, and its assembly into a channelling complex represents a higher-order modular organisation."

DEFS[294] = "Modules are not explicitly defined; the paper examines learning without neurons in physical systems — non-biological networks that adapt through mechanical or electrical relaxation. In biological contexts, the learning-like behaviour of physical modules composed of network elements corresponds to adaptive changes in module-level response properties. The paper suggests that modular physical systems can implement learning through self-organisation of inter-element interactions."

DEFS[295] = "Modules are microbial community modules — groups of co-occurring gut microbial taxa that constitute stable community sub-networks in the intestinal microbiome. The paper examines how triclosan exposure rapidly restructures these microbial modules, disrupting co-occurrence relationships and community composition. Module structure before and after triclosan exposure is characterised by co-occurrence network analysis of 16S rRNA amplicon data."

DEFS[296] = "Modules are protein complexes; Hakai is identified as a subunit required for stabilisation of the core m6A methyltransferase writer complex. The writer complex module — comprising METTL3, METTL14, WTAP, Hakai, and associated factors — constitutes the functional unit for m6A methylation deposition on mRNA. Loss of Hakai destabilises the entire complex module. The module is defined by co-complex membership and shared functional requirement for m6A methylation."

DEFS[297] = "Modules are protein interaction communities detected at proteome scale in human cells. The paper systematically maps the human interactome using multiple complementary methods and identifies dense subgraphs corresponding to protein complexes and functional modules. Each module is a group of proteins with high interaction confidence and shared biological function, contributing to a comprehensive modular map of human cellular organisation."

DEFS[298] = "Modules are neuronal circuit modules — groups of anatomically and functionally connected neurons in the ventral hippocampus that process emotional information. The paper characterises the circuit and molecular architecture of ventral hippocampal networks, identifying distinct neural modules mediating anxiety, social behaviour, and memory. Each circuit module is defined by its characteristic connectivity, molecular identity, and functional contribution to affective behaviour."

DEFS[299] = "Modules are not explicitly defined; the paper examines how NRF2 activates a partial epithelial-mesenchymal transition in cancer cells. The NRF2-EMT regulatory module — comprising NRF2 target genes and EMT transcription factors — constitutes a co-regulated functional module activated in oxidatively stressed cancer cells. The paper characterises how partial EMT regulatory module activation mediates intermediate cell states associated with metastatic competence."

DEFS[300] = "Modules are not explicitly defined; the paper surveys local and global network alignment methods for biological networks. In the context of network alignment, conserved subgraphs across species correspond to evolutionarily conserved functional modules. The paper argues that reconciling local (conserved motif) and global (whole-network) alignment approaches requires a unified view of biological module conservation across species."

DEFS[301] = "Modules are not explicitly defined; the paper describes a local regulatory T cell feedback circuit maintaining immune homeostasis. The feedback circuit — comprising regulatory T cells, self-reactive conventional T cells, and their molecular signals — constitutes a functional regulatory module performing local immune tolerance. The module is defined by the set of cell types and their signalling interactions that collectively implement the feedback control of local immune activation."

DEFS[302] = "Modules are not explicitly defined; the paper examines cycle structure in complex networks. Network cycles — sets of nodes forming closed paths — are structural features that influence module boundaries and network dynamics. Dense groups of cycles within a network subgraph contribute to module cohesion, while cycles spanning multiple modules affect inter-module communication. The paper characterises how cycle structure shapes modular network organisation and dynamics."

DEFS[303] = "Modules are not explicitly defined; the paper identifies DUSP4 and DUSP6 as a digenic dependency in MAPK pathway-driven cancers. DUSP4 and DUSP6 constitute redundant components within the MAPK negative feedback module — a regulatory sub-circuit controlling ERK activity. The paper shows that simultaneous loss of both paralogs within this feedback module creates synthetic lethality, demonstrating within-module functional redundancy as a determinant of cancer cell viability."

DEFS[304] = "Modules are not explicitly defined; the paper compiles a compendium of genetic modifiers of mitochondrial dysfunction. The mitochondrial respiratory chain and associated regulatory networks constitute functional modules whose dysfunction is modified by genetic background. The paper identifies genetic modules (sets of modifier genes) that either suppress or enhance mitochondrial disease phenotypes, revealing the network context of mitochondrial function."

DEFS[305] = "Modules are protein sub-complexes; the eukaryotic mRNA 3'-end processing machinery is a modular assembly of distinct sub-complexes (CPSF, CstF, CF I, CF II, Poly(A) Polymerase) each constituting a functional module with defined enzymatic or regulatory roles in pre-mRNA cleavage and polyadenylation. The paper characterises the structural architecture of this modular processing machine by cryo-EM, revealing how modules are organised and interact."

DEFS[306] = "Modules are not explicitly defined; the paper reviews how modifier genes and network resilience shape the genetics of health. Genetic network modules — groups of genes whose interactions collectively determine phenotypic robustness — vary in their resilience to perturbation. The paper examines how within-module genetic redundancy and between-module connectivity determine the phenotypic consequences of disease-causing mutations in the context of genetic background."

DEFS[307] = "Modules are microbial network modules — groups of co-occurring microbial taxa that form distinct community sub-networks in microbiome data. The paper reviews how network-based approaches define emergent properties of microbiomes, with modules corresponding to ecological guilds or habitat-specific assemblages. Modules are identified by community detection algorithms applied to microbial co-occurrence networks and interpreted in terms of shared ecological functions."

DEFS[308] = "Modules are protein interaction complexes — stable assemblies of physically interacting proteins detected by in vivo cross-linking mass spectrometry. The paper maps comprehensive protein interaction landscapes in living human cells, identifying modules defined by direct cross-linked contact interfaces. Each detected module corresponds to a protein assembly whose subunit composition and spatial arrangement are determined at proteome scale."

DEFS[309] = "Modules are not explicitly defined; the paper examines reciprocal effects of the 16p11.2 chromosomal deletion and duplication on neurocognitive and metabolic phenotypes. Gene sets within the 16p11.2 locus and their interaction partners constitute functional modules whose dosage imbalance drives pleiotropic phenotypes. The paper characterises how modular gene network effects of copy number variation propagate through molecular interaction networks to produce diverse phenotypic consequences."

DEFS[310] = "Modules are not explicitly defined; the paper reviews cascading failures in complex networks. Network modules — dense, internally connected subgraphs — are relevant because cascading failures tend to propagate along inter-module connections while being partially buffered within modules by redundant intra-module paths. The paper characterises how modular network architecture influences the propagation and containment of cascading failures across diverse network types."

DEFS[311] = "Modules are not explicitly defined; the paper characterises redox-dependent gating of the voltage-dependent anion channel (VDAC) by the outer mitochondrial membrane protein mitoNEET. The mitoNEET-VDAC interaction constitutes a functional regulatory module controlling mitochondrial permeability in response to cellular redox state. The module is defined by direct protein-protein interaction and shared functional requirement for redox-sensing of mitochondrial outer membrane permeability."

DEFS[312] = "Modules are multienzyme complexes — metabolic enzyme assemblies that spatially organise sequential reactions in cells. The paper reviews how metabolic multienzyme complexes (metabolons) are organised in living cells to enable substrate channelling and improve catalytic efficiency. Each metabolon constitutes a functional module defined by the physical co-association of enzymes catalysing sequential steps in a metabolic pathway."

DEFS[313] = "Modules are not explicitly defined; the paper examines how 'community smells' — organisational anti-patterns in software development teams — influence technical debt. In the software engineering context, modules are software components (classes, packages) that should ideally have low coupling and high cohesion. Community smells disrupt modular boundaries by creating inappropriate inter-team dependencies that translate into tangled code modules with high coupling."

DEFS[314] = "Modules are structural sub-complexes of SMC (Structural Maintenance of Chromosomes) complexes — specifically, the folded conformation of MukBEF and cohesin sub-assemblies. The paper characterises how the SMC heterodimer, kleisin, and HAWK/HEAT subunits constitute distinct structural modules that adopt a folded arrangement enabling DNA loop extrusion. Each structural module is defined by stable co-complex membership and functional contribution to the SMC ATPase mechanism."

DEFS[315] = "Modules are not explicitly defined; the paper reviews applications of single-cell and bulk RNA-seq in tumour immunology. Transcriptionally defined immune cell types and tumour cell sub-populations constitute functional modules of the tumour immune microenvironment. The paper characterises how transcriptomic approaches identify and characterise these cellular modules and their interactions in the context of cancer immunotherapy."

DEFS[316] = "Modules are protein complex modules; the paper characterises how the TRiC/CCT chaperonin associates with the prefoldin co-chaperone through a conserved interaction interface. TRiC/CCT and prefoldin constitute distinct but cooperating functional modules in the eukaryotic chaperone network. Each module is defined by its subunit composition and functional role — prefoldin as a substrate-capturing module and TRiC/CCT as the ATP-dependent folding chamber module."

DEFS[317] = "Modules are not explicitly defined; the paper examines a paradox in epilepsy genetics where potassium channel gain-of-function mutations cause both epileptic and non-epileptic phenotypes. The neuronal excitability regulatory module — comprising voltage-gated ion channels, leak channels, and their regulators — collectively determines action potential threshold and network excitability. The paper characterises how within-module compensatory interactions can produce counter-intuitive phenotypes from apparently hyperactivating mutations."

DEFS[318] = "Modules are gene regulatory modules — groups of co-regulated genes controlled by hub transcription factors with many targets. The paper presents enhanced gene regulatory network construction methods that incorporate hub gene information to improve module boundary detection. Each regulatory module is defined by shared transcription factor binding and co-regulated expression, with hub TFs serving as module organisers."

DEFS[319] = "Modules are not explicitly defined; the paper examines routing strategies in brain networks. Brain network modules — communities of brain regions with high within-module connectivity — serve as routing units for neural signal propagation. The paper characterises how different routing strategies (shortest path, diffusion, navigation) exploit modular brain network structure to transmit signals between distant brain regions."

DEFS[320] = "Modules are neuronal circuits — anatomically and functionally connected groups of neurons in the barrel cortex that process whisker sensory information. The paper characterises how thalamo-cortical and cortico-cortical circuit modules are organised to transform sensory input into perception. Each circuit module is defined by its characteristic connectivity, layer composition, and functional contribution to whisker sensory processing."

DEFS[321] = "Modules are not the primary biological concept; quality-diversity optimisation produces archives of solutions that may correspond to modular phenotype spaces in evolved biological systems. In biological applications, behavioural descriptor dimensions can correspond to modular phenotypic traits that can be independently varied. The paper reviews how QD optimisation explores modular phenotype spaces to produce diverse, high-quality solution archives."

DEFS[322] = "Modules are communities of brain regions identified by network clustering of intrinsic resting-state functional connectivity. The paper examines how modular brain network structure — specifically the degree to which the resting brain is organised into distinct functional modules — correlates with general intelligence across individuals. A module is defined as a group of brain regions with high within-module and low between-module functional connectivity."

DEFS[323] = "Modules are communities of brain regions — groups of brain areas with denser within-community than between-community functional or structural connectivity. The paper reviews community detection algorithms applied to brain graphs, comparing algorithmic choices and their implications for neuroscientific interpretation. Modules are defined algorithmically by optimising community quality metrics (e.g., modularity Q) applied to brain connectivity matrices."

DEFS[324] = "Modules are not explicitly defined; the paper examines macroecological trends in modularity of seed-dispersal networks across biomes and human impact gradients. Ecological interaction modules — groups of plant and animal species that interact more with each other than with species in other modules — are defined by community detection algorithms applied to bipartite mutualistic networks. The paper characterises how human disturbance affects module structure and nestedness in seed-dispersal networks."

DEFS[325] = "Modules are functional communities of brain regions identified by topological filtering of dynamic functional brain networks. The paper uses persistent homology and topological data analysis to extract robust module structure from time-varying functional connectivity matrices. Each module corresponds to a group of brain regions with persistently high within-module connectivity across dynamic network states, revealing stable functional organisation underlying brain dynamics."

DEFS[326] = "Modules are not explicitly defined; the paper characterises BAP31 as an ER membrane protein that regulates mitochondrial function via interaction with the mitochondrial outer membrane protein Tom40. The BAP31-Tom40 interaction complex constitutes a functional module at ER-mitochondria contact sites. This ER-mitochondria bridge module is defined by physical protein-protein interaction and shared functional requirement for mitochondrial homeostasis."

DEFS[327] = "Modules are not explicitly defined; the paper describes a well-ordered molecular programme for lateral root formation in Arabidopsis. The lateral root organogenesis programme — comprising a defined sequence of transcription factor activation events and developmental transitions — constitutes a functional regulatory module. Each step in the module is defined by the activation of a specific gene regulatory sub-circuit controlling a discrete phase of lateral root development."

DEFS[328] = "Modules are gene co-expression modules — groups of genes whose expression levels are highly correlated across samples, identified by weighted gene co-expression network analysis. The paper examines how within-module connectivity (hub gene connectivity) determines the heritability of gene expression variation. Highly connected hub genes within modules are shown to have higher heritability, linking network module topology to genetic architecture."

DEFS[329] = "Modules are not explicitly defined; the paper examines graded regulation of cellular quiescence depth between proliferation and senescence. The quiescence regulatory module — comprising cyclins, CDK inhibitors, transcription factors (E2F, Rb), and growth factor signalling inputs — constitutes a regulatory circuit controlling the depth and reversibility of quiescent states. The paper characterises how cells tune module activity to adopt different quiescence depths with distinct reactivation potentials."

DEFS[330] = "Modules are not explicitly defined; scTenifoldKnk is a virtual knockout tool that infers gene function by simulating node removal from single-cell gene regulatory network reconstructions. Gene regulatory modules — dense subgraphs in the network corresponding to co-regulated gene sets — are used to predict the downstream transcriptional consequences of gene knockouts. The tool uses network module structure to propagate perturbation effects through the regulatory network."

DEFS[331] = "Modules are not explicitly defined; the paper reviews the function and regulation of zinc in the brain. Zinc-dependent signalling networks in neurons constitute functional regulatory modules linking zinc availability to neurotransmission, synaptic plasticity, and neuroprotection. The paper characterises how zinc-binding proteins and transporters form distinct functional modules that control zinc homeostasis and signalling in specific brain regions and cell types."

DEFS[332] = "Modules are functional communities of brain regions identified by resting-state fMRI connectivity analysis. The paper examines individual differences in brain module structure and how modules vary over time (time-varying modularity). Each module is a group of brain regions with higher within-module than between-module functional connectivity. The paper characterises how the temporal dynamics and individual variability of brain module organisation relate to cognitive function."

DEFS[333] = "Modules are not explicitly defined; Babelomics provides tools for functional analysis of genomics data. Gene sets derived from biological pathways, gene ontology terms, and regulatory networks serve as predefined functional modules for enrichment analysis. The paper reviews how Babelomics integrates these module databases with statistical enrichment methods for interpreting omics data."

DEFS[334] = "Modules are separable, reusable sub-networks within deep learning models — functional components that can be independently trained and transferred across tasks. The paper reviews modular deep learning architectures including mixture-of-experts, adapter modules, and hypernetworks. In biological applications, modular neural network components correspond to domain-specific feature extractors or classifiers analogous to functional modules in biological regulatory networks."

DEFS[335] = "Modules are protein complexes; ZMYND8 is shown to co-localise with the NuRD chromatin remodelling complex at specific target gene promoters and enhancers. The NuRD-ZMYND8 co-regulatory module constitutes a functional chromatin remodelling assembly at DNA damage sites. The module is defined by stable co-complex membership and shared functional role in Poly(ADP-Ribose) polymerase-dependent transcription regulation."

DEFS[336] = "Modules are not explicitly defined; the paper bridges traditional ethnopharmacology and modern drug discovery, examining how natural compounds interact with molecular targets. Signalling pathway modules and protein complex targets constitute the functional units through which natural compound interventions produce therapeutic effects. Network pharmacology provides a framework for mapping compound-module interactions to understand multi-target mechanisms."

DEFS[337] = "Modules are not explicitly defined; the paper describes MAGE multiplex genome engineering in yeast for metabolic engineering. Sets of co-edited genomic loci targeting a shared metabolic pathway constitute modular editing targets. The paper demonstrates that simultaneously editing multiple components within a functional metabolic module achieves more complete pathway reprogramming than iterative single-target approaches."

DEFS[338] = "Modules are protein complexes detected by structural proteomics using cross-linking mass spectrometry. Each detected protein community — a stable assembly of physically interacting proteins — constitutes a functional module performing a defined cellular role. The paper provides a comprehensive map of modular protein organisation in a thermophilic archaeon, revealing conserved modular principles of cellular machinery."

DEFS[339] = "Modules are not explicitly defined; the paper reviews multifunctional soft machines based on stimuli-responsive hydrogels for biomedical applications. Engineered soft devices combine gel modules with distinct stimuli-response properties (thermal, pH, light, redox) into composite systems. Each responsive gel component constitutes a functional module whose independent operation enables multi-modal sensing and actuation in the overall soft machine."

DEFS[340] = "Modules are protein interaction communities in the human interactome; moonlighting proteins are those that participate in multiple distinct modules simultaneously, occupying bridging positions between community boundaries. The paper identifies extreme moonlighting proteins with the highest multi-module membership using network topology and associates their degree of multi-modularity with essentiality and disease involvement."

DEFS[341] = "Modules are multienzyme complexes — physically associated groups of metabolic enzymes performing sequential reactions in glucose metabolism. The paper identifies a glucose metabolism metabolon in living cells through proximity labelling and co-immunoprecipitation. The metabolic module is defined by direct protein-protein interactions, co-localisation in the cytoplasm, and functional cooperativity enabling substrate channelling between sequentially acting enzymes."

DEFS[342] = "Modules are not explicitly defined; the paper reviews clinical metabolomics for inborn errors of metabolism diagnosis. Metabolic pathway modules — groups of enzymes catalysing sequential reactions within a defined pathway — are the units disrupted in inborn errors of metabolism. Clinical metabolomics identifies diagnostic metabolite signatures that reflect disruption of specific metabolic modules, enabling targeted diagnosis and monitoring."

DEFS[343] = "Modules are not explicitly defined; the paper examines nonlinear delay differential equations as models of biological regulatory systems. Regulatory feedback loops and circuit motifs in gene networks and signalling cascades constitute functional modules whose dynamical behaviour is determined by delay parameters and nonlinear kinetics. The paper characterises how these circuit modules produce oscillations, multistability, and other dynamical phenotypes relevant to biological regulation."

DEFS[344] = "Modules are morphological modules — semi-independent groups of skeletal traits whose evolutionary rates can diverge. The paper provides a new phylogenetic statistical test for comparing evolutionary rates across multiple high-dimensional morphological trait matrices. The method enables detection of rate heterogeneity between modules and testing of hypotheses about which trait groups evolve together or independently."

DEFS[345] = "Modules are protein complexes predicted by AI-assisted structural proteomics combining AlphaFold structure predictions with experimental co-fractionation data. Each predicted complex constitutes a functional module defined by structural complementarity between subunits and physical co-association. The paper demonstrates how computational structure prediction can guide identification of protein complex modules at proteome scale."

DEFS[346] = "Modules are morphological modules — semi-independent groups of skeletal traits (pelvic, dorsal, and lateral plate armour; jaw morphology) that have convergently evolved across independent marine-to-freshwater stickleback transitions. The paper maps the genetic architecture of these morphological modules using improved genome assemblies, identifying quantitative trait loci controlling specific modules. Convergent evolution of the same modules across populations demonstrates the modular organisation of the stickleback adaptive toolkit."

DEFS[347] = "Modules are not explicitly defined; the paper evaluates deep neural networks for visual recognition tasks. In the context of biological visual system modelling, modular sub-networks (e.g., V1-like edge detectors, higher visual area object recognisers) correspond to functional modules of visual cortex. The paper discusses whether deep network internal representations recapitulate the modular functional specialisation of biological visual cortical areas."

DEFS[348] = "Modules are not explicitly defined; the paper examines HDAC6 inhibition as a treatment for GARS-mutant Charcot-Marie-Tooth disease. The axonal transport machinery — comprising kinesin and dynein motors, associated regulatory proteins, and the cytoskeletal substrate — constitutes a functional module whose activity is impaired by GARS mutations. HDAC6 inhibition rescues this transport module by modifying tubulin acetylation, restoring module function."

DEFS[349] = "Modules are not explicitly defined; the paper reviews extracellular NAMPT (eNAMPT) as a cancer metabolic biomarker and therapeutic target. The NAD+ biosynthesis and salvage pathway constitutes a functional metabolic module whose components, including NAMPT, are co-ordinately regulated in cancer cells. The paper characterises how eNAMPT acts as a cytokine-like extracellular signal that activates downstream survival signalling modules in tumour cells."

DEFS[350] = "Modules are plant functional trait modules — semi-independent groups of traits that are statistically connected within a module but not strongly connected to traits in other modules. The paper examines the robustness of within-module trait connections across environmental gradients and growth forms, assessing whether module structure is consistent across ecological contexts. Modules are defined by conditional independence networks applied to plant functional trait data."

DEFS[351] = "Modules are not explicitly defined; the paper describes real-time imaging of a single-molecule enzyme cascade using a DNA origami scaffold. Co-localised enzyme pairs on the DNA origami substrate constitute a minimal functional module enabling substrate channelling between sequentially acting enzymes. The module is defined by spatial co-localisation on the scaffold and functional cooperativity in converting substrate to product."

DEFS[352] = "Modules are not explicitly defined; the paper reviews anti-ageing strategies for neurodegenerative diseases, examining molecular mechanisms of neuronal ageing and degeneration. Cellular process modules — protein quality control, mitochondrial function, neuroinflammation, synaptic maintenance — are the functional units whose deterioration drives neurodegeneration. The paper characterises how targeting individual modules or their regulatory interactions represents a strategy for intervention."

DEFS[353] = "Modules are not explicitly defined; the paper bridges ecological decision-making and subjective experience in animals. Neural circuit modules mediating specific decision components — value representation, option comparison, action selection — constitute the functional units of analysis. The paper discusses how modular circuit architecture for decision-making evolved in the context of ecological demands and how different modules contribute to adaptive behavioural flexibility."

DEFS[354] = "Modules are transcriptomically defined neuronal sub-types — groups of circadian neurons with shared gene expression profiles constituting distinct cell-type modules within the Drosophila clock circuit. The paper constructs a transcriptomic taxonomy of clock neurons around the circadian cycle, identifying modules of neurons with shared molecular identity, temporal expression patterns, and potentially shared circuit functions in circadian timekeeping."

DEFS[355] = "Modules are structural sub-complexes of the nuclear pore complex (NPC); the FG-nucleoporin module — a collective of intrinsically disordered proteins lining the NPC central channel — constitutes a functional module for selective nucleocytoplasmic transport. The paper examines how FG-repeat interactions stabilise NPC structure and how the collective properties of this module produce selective transport barriers. The module is defined by shared FG-repeat architecture and co-localisation within the NPC central channel."

DEFS[356] = "Modules are not explicitly defined; the paper uses evolutionary proteomics to uncover ancient associations between the ciliary proteome and signalling pathways. The ciliary proteome constitutes a functional module — a coherent set of proteins co-evolved for cilium assembly, maintenance, and signalling. The paper identifies conserved signalling pathway modules that were ancestrally associated with cilia before the divergence of major eukaryotic lineages."

DEFS[357] = "Modules are not explicitly defined; the paper reviews the clinical pharmacology of reactive oxygen species (ROS). Redox regulatory systems — antioxidant enzymes, thioredoxin/peroxiredoxin networks, NADPH oxidase complexes — constitute functional modules collectively controlling cellular redox balance. The paper characterises how pharmacological interventions targeting specific redox modules can be harnessed therapeutically in diseases characterised by oxidative stress."

DEFS[358] = "Modules are co-expression and co-abundance modules identified across independent Alzheimer's disease cohorts by network analysis. The paper reports commentary on a multi-scale analysis finding disrupted molecular, genetic, and network modules consistent across cohorts. Each module corresponds to a group of genes or proteins with correlated expression mapping to a specific biological sub-system relevant to AD pathology."

DEFS[359] = "Modules are not explicitly defined; the paper reviews DIA-based proteomics data acquisition and analysis. Protein complexes and co-regulated protein sets identified from DIA proteomics data constitute functional modules of the proteome. The paper provides methodology guidelines for accurately quantifying these protein modules across conditions using data-independent acquisition workflows."

DEFS[360] = "Modules are morphological modules — semi-independent groups of anatomical traits whose developmental plasticity guides evolutionary trajectories. The paper examines how developmental variation within modules provides raw material for natural selection, with developmental modules constraining and directing evolutionary change. Modules are defined by within-module phenotypic integration arising from shared developmental processes."

DEFS[361] = "Modules are not explicitly defined; the paper analyses genomic determinants of protein abundance variation in colorectal cancer using proteogenomics. Co-regulated protein sets controlled by shared genomic alterations (copy number changes, driver mutations) constitute expression modules whose dysregulation defines tumour molecular subtypes. The paper characterises which protein abundance modules are driven by specific genetic events in colorectal tumours."

DEFS[362] = "Modules are not explicitly defined; the paper reviews CDK regulatory mechanisms and therapeutic opportunities. Cyclin-CDK-substrate complexes constitute functional modules controlling cell cycle transitions, with different cyclin partners specifying distinct substrate modules. The paper characterises how novel CDK regulatory proteins modulate module activity to control cell proliferation and how these modules can be targeted in cancer therapy."

DEFS[363] = "Modules are genetic interaction modules — groups of genes linked by complex genetic interactions reflecting shared pathway membership or compensatory relationships between paralogs. The paper examines how complex genetic interactions arise between whole-genome duplicate gene pairs and reveal the functional redundancy within modular genetic networks in yeast. These interaction patterns define the boundaries of functional modules that buffer against gene loss."

DEFS[364] = "Modules are not explicitly defined; the paper reviews link prediction methods applied to drug discovery networks. Pathway modules and protein interaction communities in drug-target networks are the units of analysis for identifying candidate drug-target links. Module membership provides a structural prior for predicting which drug-target associations are most likely to represent true pharmacological interactions."

DEFS[365] = "Modules are co-expressed protein modules identified by network analysis of multi-layer Alzheimer's disease brain proteomics data across brain regions and disease stages. Each module corresponds to a group of proteins with correlated abundances reflecting shared regulation, complex membership, or pathway co-participation. The paper uses these modules to resolve the biological processes disrupted across AD stages and identify module-level biomarkers of disease progression."

DEFS[366] = "Modules are not explicitly defined; the paper studies how ribosome stalling during selenoprotein translation exposes a ferroptosis vulnerability. The selenoprotein synthesis module — comprising SECIS elements, SECISBP2, EFSec elongation factor, and the dedicated tRNA — constitutes a specialised translation module for selenocysteine incorporation. Stalling of this module during cellular stress connects selenoprotein synthesis to ferroptosis through a non-canonical mechanism."

DEFS[367] = "Modules are functional kinase groups — clusters of kinases with shared interaction partners, substrates, or cellular roles. The kinase interaction network organises the human kinome into functional modules by physical and genetic interaction profile similarity. The paper expands kinase module annotations by identifying novel kinase-substrate interactions and disease-relevant kinase modules."

DEFS[368] = "Modules are functional protein groups in E. coli whose expression is co-ordinately controlled and whose members work together in defined cellular processes. The paper maps the functional proteome landscape of E. coli, associating each protein with pathways, complexes, and regulatory networks. Protein complexes and metabolic pathway assemblies constitute the modular units of the E. coli proteome, each characterised by defined composition and cellular role."

DEFS[369] = "Modules are not explicitly defined; the paper reviews tools for integrating, visualising, and analysing genomics data in biological network contexts. Biological pathway modules and protein interaction communities serve as the predefined reference units for enrichment analysis and network visualisation. The paper describes how these reference modules enable biological interpretation of high-throughput datasets through network-based analytical frameworks."

DEFS[370] = "Modules are not explicitly defined; the paper examines cognitive ageing and time perception. In the brain network context, functional modules — communities of brain regions mediating temporal processing — constitute the units of analysis. The paper uses Bayesian optimisation models to characterise how age-related changes in brain network module properties affect time perception and cognitive timing accuracy."

DEFS[371] = "Modules are structural sub-complexes of the nuclear pore complex (NPC); the paper examines the stability, dynamics, and architecture of NPC sub-complexes. The scaffold nucleoporin ring, FG-nucleoporin module, and nuclear basket together constitute modular sub-assemblies of the NPC. The paper characterises how these structural modules are dynamically assembled and maintained throughout the cell cycle."

DEFS[372] = "Modules are protein complexes; the paper predicts that scaffolding of protein complex assembly is a prevalent function of long non-coding RNAs. lncRNAs that simultaneously bind multiple protein complex subunits constitute RNA-based scaffolding modules that co-ordinate the assembly of functional protein modules at specific genomic loci. Each scaffolded complex represents a module defined by lncRNA-mediated co-localisation of co-operating proteins."

DEFS[373] = "Modules are functionally defined gene sets constituting a maternal functional module — a group of maternally deposited gene products collectively required for the oocyte-to-embryo transition in mammals. The paper identifies the composition and regulation of this maternal module, characterising its role in early embryonic development. The module is defined by temporal co-expression in oocytes and shared functional requirement for pre-ZGA development."

DEFS[374] = "Modules are functional communities of brain regions — groups of brain areas with high co-activation forming modules in task-related functional networks. The paper tracks how functional brain modules reorganise as cognitive load increases, characterising the transition from segregated modular states during rest to more integrated states during demanding tasks. Module flexibility — the tendency of brain regions to switch module membership — predicts individual cognitive performance."

DEFS[375] = "Modules are protein complexes; the COMMD/CCDC22/CCDC93 (CCC) complex constitutes a functional module for regulating endosomal phosphoinositide composition and cargo recycling. The CCC module interacts with the WASH complex and retriever sub-complex to co-ordinate endosomal sorting. The module is defined by stable co-complex membership, shared subcellular localisation on endosomes, and collective functional requirement for PI(3)P regulation."

DEFS[376] = "Modules are not explicitly defined; the paper addresses host-aware synthetic biology, examining how genetic circuit design must account for host cell state. Genetic circuit modules — functional units composed of promoters, regulatory elements, and gene cassettes — have context-dependent performance due to competition for host cellular resources (RNAP, ribosomes, metabolites). The paper provides frameworks for modelling host-module interactions and designing circuits robust to host context."

DEFS[377] = "Modules are not explicitly defined; DeepFunc is a deep learning framework for protein function prediction. Protein interaction modules — groups of proteins with shared network topology and similar functional annotations — provide the network context that improves function prediction accuracy. The framework integrates protein interaction module membership with sequence features to infer protein function categories from the Gene Ontology."

DEFS[378] = "Modules are functional protein groups in bacterial protein interaction networks — densely connected sub-networks corresponding to protein complexes and metabolic pathways. The paper analyses properties of bacterial protein networks including modularity, clustering, and small-world organisation. Network modules correspond to known protein complexes, biosynthetic pathways, and multi-protein machines, and their topological properties reflect the constraints of bacterial cellular organisation."

DEFS[379] = "Modules are not explicitly defined; the paper presents a topology-potential method for identifying essential proteins in protein interaction networks. Hub proteins within dense network modules — nodes with high within-module connectivity — are predicted essential because their removal would destabilise multiple connected functional modules simultaneously. The topology potential captures both local and global module connectivity to rank protein essentiality."

DEFS[380] = "Modules are not explicitly defined; the paper studies how METTL3 acetylation regulates its nuclear activity and inhibits cancer metastasis. The m6A methyltransferase writer complex — METTL3, METTL14, WTAP, and nuclear interaction partners — constitutes the functional module for m6A methylation. Post-translational acetylation of METTL3 fine-tunes the nuclear retention and activity of this writer complex module to control metastasis-relevant gene expression."

DEFS[381] = "Modules are not explicitly defined; the paper studies Rab5 and Alsin in stress-activated cytoprotective signalling at mitochondria-associated membranes. The Rab5-positive endosomal-mitochondria contact site module constitutes a functional signalling platform for stress response co-ordination. The module is defined by the co-localisation of Rab5 and Alsin at membrane contact sites and their shared functional requirement for neuroprotective signalling."

DEFS[382] = "Modules are functional communities of brain regions — groups of brain areas with correlated activity forming modules in longitudinal resting-state functional networks. The paper tracks how cortical functional module organisation changes over time in a patient cohort, characterising reorganisation as a marker of disease progression or recovery. Module boundaries and within-module connectivity are used as imaging biomarkers of cortical network state."

DEFS[383] = "Modules are not explicitly defined; the paper studies how an EBV-encoded miRNA promotes gastric cancer invasion by inducing EMT. The EMT regulatory module — comprising EMT transcription factors (ZEB1, SNAI1), their target genes, and upstream miRNA regulators — is co-ordinately activated by viral miRNA expression. The paper characterises the molecular pathway by which viral reprogramming of this regulatory module drives tumour cell invasion and metastasis."

DEFS[384] = "Modules are transcriptional regulatory modules — groups of transcription factors and co-regulated target genes controlling vascular cambium development in Arabidopsis. The paper constructs a regulatory framework by identifying co-expressed gene modules and their upstream transcription factor controllers at different cambium developmental stages. Each module corresponds to a regulatory programme specifying a distinct phase of secondary growth."

DEFS[385] = "Modules are densely connected subgraphs in biological interaction networks, identified by higher-order structural clustering (HiSCF). The paper proposes a method leveraging higher-order motif patterns to detect modules that are missed by pairwise community detection. In protein interaction networks, these higher-order modules correspond to protein complexes and functional sub-networks sharing multi-node interaction patterns."

DEFS[386] = "Modules are morphological modules — semi-independent groups of traits defined by patterns of within-module integration and between-module independence. The paper evaluates and compares different metrics and methods for assessing modularity signal strength in morphological datasets, including RV coefficients, covariance ratio, and likelihood-based approaches. Modules are defined statistically by the degree to which within-module trait covariation exceeds between-module covariation."

DEFS[387] = "Modules are not explicitly defined; the paper characterises tricalbins as tethers at ER-PM contact sites that facilitate lipid transfer between organelle membranes. The ER-PM contact site tethering module — comprising tricalbins and associated proteins — constitutes a functional unit for phospholipid homeostasis. The module is defined by co-localisation at contact sites and collective contribution to membrane lipid flux between the ER and plasma membrane."

DEFS[388] = "Modules are gene co-expression modules identified by network analysis across species. The paper uses phylogenomic comparison of co-expression networks to identify evolutionarily conserved modules reflecting ancient co-regulatory programmes. Conserved modules are interpreted as functionally constrained units of gene regulation, while lineage-specific modules represent evolutionary innovations in gene co-expression organisation."

DEFS[389] = "Modules are functional communities of brain regions — groups of brain areas whose connectivity patterns support specific cognitive functions. The paper examines how brain network module architecture influences individual learning capacity, treating module flexibility (the tendency to switch community affiliations) and integration (cross-module connectivity) as predictors of learning ability. The paper connects network module properties to quantitative educational neuroscience."

DEFS[390] = "Modules are structural sub-complexes of the condensin SMC complex; the paper characterises cryo-EM structures revealing a subunit flip-flop mechanism. The SMC heterodimer, kleisin, and HEAT-repeat subunits constitute distinct structural modules whose relative positions alternate between two states during the ATP hydrolysis cycle. The paper shows how these module rearrangements are coupled to DNA loop extrusion activity."

DEFS[391] = "Modules are microbial community assemblages in plastisphere biofilms — co-occurring groups of taxa forming distinct community modules on plastic debris in freshwater wetland ecosystems. The paper characterises biofilm formation, community structure, and functional potential of these microbial modules. Module composition is shaped by plastic polymer type, environmental conditions, and ecological interactions among taxa."

DEFS[392] = "Modules are metabolic pathway modules within genome-scale metabolic models of animals. The paper describes reconstruction and use of animal metabolic networks for predicting physiological and pathological phenotypes. Each metabolic pathway module — a group of enzymatic reactions performing a defined biosynthetic or catabolic function — can be independently analysed or perturbed to understand metabolic physiology."

DEFS[393] = "Modules are gene regulatory modules — groups of co-regulated genes controlled by shared transcription factor binding sites or regulatory elements. The paper examines how mechanisms of mutational robustness in transcriptional regulation maintain module-level gene expression despite sequence variation. Within-module redundancy in binding sites and regulatory inputs buffers modules against the phenotypic effects of individual regulatory mutations."

DEFS[394] = "Modules are separable computational sub-networks within artificial neural network architectures that can be independently trained, transferred, or reused. The paper reviews modularisation techniques including mixture-of-experts, capsule networks, modular meta-learning, and slot-based architectures. In biological analogies, these modular neural network components correspond to functional sub-systems performing distinct computational operations on defined input types."

DEFS[395] = "Modules are not explicitly defined; the paper functionally and evolutionarily characterises a secondary metabolite biosynthesis gene cluster. Such biosynthetic gene clusters constitute functional metabolic modules — groups of co-regulated, co-localised genes whose products collectively synthesise a specific secondary metabolite. The cluster module is defined by shared chromosomal location, co-expression, and functional cooperativity in producing the metabolic end product."

DEFS[396] = "Modules are disease modules — localised subnetworks of the human interactome in which proteins associated with a given disease cluster together. The paper reviews interactome-based approaches to human disease, using network proximity of disease genes as a measure of disease module overlap. Drug targets are prioritised by their topological proximity to the disease module in the protein interaction network."

DEFS[397] = "Modules are functional communities of brain regions — groups of brain areas with correlated activity forming modules in developing functional networks. The paper examines how the hierarchical development of functional brain module systems supports the maturation of executive function in children. Module segregation and integration over development are the network-level metrics linked to cognitive maturation."

DEFS[398] = "Modules are not explicitly defined; the paper presents amortised inference methods for causal structure learning in graphical models. In the context of gene regulatory networks, regulatory modules — groups of genes controlled by shared regulators — constitute the causal sub-structures being inferred. Amortised methods enable efficient learning of module-level causal relationships from observational and interventional data."

DEFS[399] = "Modules are not explicitly defined; the paper examines spatial and temporal signal processing by MAPK pathways. The MAPK signalling cascade (RAS-RAF-MEK-ERK) and its associated scaffolding proteins constitute an integrated signalling module performing defined computational operations (pulse generation, frequency filtering, spatial gradient sensing). The paper characterises how module-level signal processing properties arise from the molecular interactions within the MAPK circuit."

DEFS[400] = "Modules are not explicitly defined; the paper examines endosome and Golgi-associated degradation (EGAD) of membrane proteins. The EGAD degradation machinery — comprising ubiquitin ligases, AAA-ATPases, and membrane-associated degradation factors — constitutes a functional module for quality control of membrane proteins. The module is defined by shared subcellular localisation and collective contribution to membrane protein turnover at endosomal-Golgi interfaces."

DEFS[401] = "Modules are not explicitly defined; the paper examines the relationship between protein-protein interaction data and protein co-expression networks. Protein complexes identified from interaction data and co-expression modules identified from expression data constitute complementary but overlapping types of functional modules. The paper characterises how converting PPI data to co-expression networks can reveal module-level properties not apparent from either data source alone."

DEFS[402] = "Modules are structural sub-complexes of SMC (Structural Maintenance of Chromosomes) complexes — cohesin, condensin, and Smc5/6 — each of which is itself a modular machine. The paper reviews the universal DNA looping mechanism and the distinct regulatory features that differentiate SMC complex modules. Each SMC complex is a functional module composed of SMC heterodimer, kleisin, and accessory HAWK/HEAT subunits with defined roles in genome organisation."

DEFS[403] = "Modules are not explicitly defined; the paper characterises a PHD/BRD/PWWP triple reader domain protein that multivalently engages histone modifications and DNA. Each reader domain (PHD, BRD, PWWP) constitutes a functional recognition module with distinct specificity for different histone marks. The multi-domain reader protein integrates signals from multiple chromatin modules simultaneously, enabling combinatorial readout of the histone code."

DEFS[404] = "Modules are not explicitly defined; the paper reviews CRISPR-based tools for manipulating genetically intractable organisms. Gene editing machinery and its genomic targets constitute functional modules for precise genome engineering. The paper characterises how modular assembly of CRISPR components (guide RNA, Cas protein, effector domain) enables targeted manipulation of specific genomic regulatory modules in diverse organisms."

DEFS[405] = "Modules are genetic circuit components — functional units (promoters, regulatory elements, coding sequences) that can be assembled in a modular fashion to engineer microbial cells with desired behaviours. The paper reviews design principles for microbial gene circuit engineering, including how modules are characterised and combined. Modularity requires that each circuit component behaves predictably when combined with other modules, a key challenge addressed by the paper."

DEFS[406] = "Modules are not explicitly defined; the paper identifies hub genes and key pathways associated with bipolar disorder. Gene co-expression modules — groups of co-regulated genes identified by weighted gene co-expression network analysis — are the units of analysis for identifying disease-associated network perturbations. Hub genes within modules associated with bipolar disorder are identified as potential biomarkers and therapeutic targets."

DEFS[407] = "Modules are not explicitly defined; the paper constructs a quantitative cellular-resolution map of oxytocin receptor distribution in the postnatal brain. Brain regions with high oxytocin receptor expression constitute functional modules of the oxytocin signalling network. The spatial map enables systematic characterisation of oxytocin receptor module distribution and its relationship to circuit function in social behaviour and stress responses."

DEFS[408] = "Modules are not explicitly defined; the paper surveys global alignment methods for protein-protein interaction networks. Conserved subgraphs identified by network alignment correspond to evolutionarily conserved functional modules. The survey evaluates how different alignment algorithms recover known conserved modules and how alignment quality metrics relate to biological relevance of identified module correspondences across species."

DEFS[409] = "Modules are microbial community modules — groups of co-occurring soil microbial taxa forming distinct sub-networks in agricultural soils. The paper examines how agricultural intensification weakens soil health and modifies microbial network module stability. Modules are identified by co-occurrence network community detection and their stability — measured by network modularity — is compared across agricultural management regimes."

DEFS[410] = "Modules are biclusters — subsets of both rows (genes/samples) and columns (conditions/genes) of a data matrix that exhibit coherent patterns simultaneously. The paper reviews biclustering methods and their applications to gene expression data, where biclusters correspond to functional modules — groups of genes co-expressed under specific conditions. Biclustering identifies condition-specific functional modules that are missed by standard clustering approaches."

DEFS[411] = "Modules are neural circuit modules — defined groups of neurons that perform distinct computational operations within the cortical microcircuit. The paper characterises a disinhibitory circuit motif — a three-neuron module comprising pyramidal cells, parvalbumin interneurons, and VIP interneurons — that enables flexible information routing in the neocortex. The disinhibitory module is defined by its characteristic connectivity pattern and functional role in gating information flow."

DEFS[412] = "Modules are protein complexes; the paper examines how cells maintain the correct stoichiometry of protein complex subunit components. Protein complexes constitute functional modules whose activity depends on the precise ratio of subunit components. The paper characterises the mechanisms (auto-regulation of subunit expression, balanced transcription, regulated protein degradation) by which cells keep protein complex module stoichiometry within functional limits."

DEFS[413] = "Modules are carboxysomes — protein-based microcompartments constituting metabolic modules for CO2 fixation in cyanobacteria and other autotrophs. Each carboxysome module encapsulates RuBisCO enzymes and carbonic anhydrase within a protein shell, creating a localised microenvironment that concentrates CO2 and improves carboxylation efficiency. The module is defined by its protein shell composition, encapsulated enzyme cargo, and functional role in carbon fixation."

DEFS[414] = "Modules are not explicitly defined; the paper examines positive feedback in mitosis duration control. The mitotic regulatory module — comprising cyclin B-CDK1, its activators (CDC25), and inhibitors (Wee1, APC/C) — constitutes a regulatory circuit whose positive feedback insulates mitosis duration from upstream signalling variations. The module is defined by the set of interacting proteins that collectively determine mitotic entry, progression, and exit timing."

DEFS[415] = "Modules are not explicitly defined; the paper presents a cell-based systems biology assessment using blood transcriptomics to monitor immune responses. Gene co-expression modules — groups of co-regulated immune genes identified by weighted co-expression network analysis — are the units of analysis for characterising immune activation states. The paper identifies modules associated with specific immune cell types and activation conditions as biomarkers of immune status."

DEFS[416] = "Modules are not explicitly defined; the paper identifies cancer cytotoxic modulators of PDE3A by predictive chemo-genomics. PDE3A and its interaction partners in cAMP signalling constitute a functional regulatory module whose perturbation mediates cytotoxicity in specific cancer cell types. The paper characterises the network context of PDE3A in the signalling module that determines sensitivity to PDE3A-targeting compounds."

DEFS[417] = "Modules are not explicitly defined; Unique Variable Analysis is a network psychometrics method to detect local dependence structures in psychological measurement networks. In the context of psychological construct networks, modules correspond to groups of items or variables that are locally dependent — sharing variance due to a common latent cause beyond the main construct. The method identifies these within-measure modules to improve measurement model specification."

DEFS[418] = "Modules are not explicitly defined; the paper examines how pathway database choice affects statistical enrichment analysis results. Pathway modules — groups of genes defined by database-specific curation criteria — differ in their composition across databases. The paper characterises how these differences in module definition lead to different enrichment analysis conclusions from the same omics data, emphasising the importance of module definition choices."

DEFS[419] = "Modules are not explicitly defined; BRIGHT is a bridging algorithm for biological network alignment. Conserved subgraphs identified by network alignment correspond to functionally conserved modules shared across species. The paper presents a method that bridges local and global alignment strategies to identify module-level correspondences between biological networks more accurately than either approach alone."

DEFS[420] = "Modules are not explicitly defined; the paper reviews current and future directions in network biology. Biological network modules — densely connected subgraphs corresponding to protein complexes, co-expression clusters, or genetic interaction groups — are the primary units of analysis in network biology. The paper discusses how advances in multi-omics data integration and network inference are expanding the resolution and accuracy of module identification."

DEFS[421] = "Modules are not explicitly defined; INGA combines interaction networks, domain annotations, and GO term associations to predict protein function. Protein interaction modules — groups of proteins with shared network neighbourhood and functional annotations — provide the context that improves function prediction accuracy. The method integrates module membership with domain-based homology signals for comprehensive protein function annotation."

DEFS[422] = "Modules are not explicitly defined; the paper examines topological requirements for robust perfect adaptation in biochemical networks. Regulatory circuit modules — including negative feedback loops, incoherent feedforward loops, and integral feedback controllers — constitute the functional network motifs enabling adaptation. The paper identifies which topological motif modules are necessary and sufficient for robust perfect adaptation, providing design principles for engineering adaptive biochemical circuits."

DEFS[423] = "Modules are not explicitly defined; GraphWorld is a benchmark framework generating synthetic graphs with controlled structural properties to evaluate GNN performance. In biological graph applications, community structure — modules of densely connected nodes — is a key structural property whose presence affects GNN performance. The paper uses synthetic graphs with varying community/module structure to systematically characterise how GNN methods respond to different modular architectures."

DEFS[424] = "Modules are not explicitly defined; the paper characterises how SARS-CoV-2 variants of concern convergently remodel the host response network. Signalling pathway modules and immune response gene modules in host cells are co-ordinately altered by viral infection. The paper uses systems-level proteomics and transcriptomics to identify which host functional modules are convergently targeted by different viral variants, revealing shared strategies for immune evasion."

DEFS[425] = "Modules are not explicitly defined; SANA uses simulated annealing for biological network alignment to identify conserved subgraphs. These conserved subgraphs correspond to evolutionarily conserved functional modules shared across species' protein interaction networks. The paper demonstrates that SANA outperforms other alignment algorithms in recovering known conserved modules by optimising a topological similarity score between aligned network regions."

DEFS[426] = "Modules are not explicitly defined; the paper identifies LIMT as a lncRNA suppressed by EGF that inhibits cancer metastasis. The EGFR signalling module — comprising EGF-EGFR, downstream MAPK and PI3K pathways, and transcriptional targets — constitutes the functional unit that regulates LIMT expression. The paper characterises how LIMT fits within the EGFR-controlled regulatory module to modulate the invasive behaviour of cancer cells."

DEFS[427] = "Modules are genetic circuit components — promoters, regulatory elements, and gene cassettes — that can be insulated from one another to enable precise, context-independent circuit assembly. The paper demonstrates that transcriptional insulator elements reduce spurious cross-talk between adjacent genetic modules, enabling reliable prediction of assembled circuit behaviour from characterised module performance. Modularity is defined as the preservation of individual module input-output behaviour upon assembly."

DEFS[428] = "Modules are not explicitly defined; the paper examines pattern recognition in nucleation kinetics of non-equilibrium self-assembly using neural network models. In biological self-assembly contexts, protein complex modules — groups of subunits that nucleate co-operatively — constitute the minimal assembly units whose kinetics are being characterised. The paper develops pattern recognition methods for identifying these assembly modules from nucleation kinetics data."

DEFS[429] = "Modules are not explicitly defined; the paper reviews graph database integration of heterogeneous biological data. Biological pathways and protein interaction communities serve as functional modules that organise the integrated database. Graph databases enable efficient query of module membership, enabling network-level analysis of how different biological data types (expression, interaction, phenotype) converge on shared functional modules."

DEFS[430] = "Modules are not explicitly defined; the paper reviews the state of the art for understanding genotype-to-phenotype mappings. In network-based perspectives on genotype-phenotype maps, gene regulatory modules and protein interaction modules constitute the functional units whose perturbation produces phenotypic change. The paper characterises how modular network organisation shapes the genotype-phenotype map and the evolvability of phenotypes."

DEFS[431] = "Modules are not explicitly defined; the paper studies transketolase (TKT) nuclear localisation and its role in promoting hepatocellular carcinoma growth. The pentose phosphate pathway module — a group of enzymes catalysing the carbon-rearranging reactions of the PPP — constitutes the metabolic module in which TKT functions. The paper characterises how nuclear TKT promotes cancer growth through mechanisms beyond its canonical metabolic module function."

DEFS[432] = "Modules are not explicitly defined; the paper studies how insulin fine-tunes self-renewal pathways in naive pluripotent stem cells. The self-renewal regulatory module — comprising pluripotency transcription factors (Nanog, Oct4, Sox2), signalling inputs (LIF, BMP4, insulin), and downstream targets — constitutes a functional regulatory circuit controlling stem cell identity. The paper characterises how insulin modulates specific components of this regulatory module to balance naive pluripotency maintenance versus differentiation."

DEFS[433] = "Modules are protein complexes and interaction communities detected across multiple mouse tissue types by systematic affinity purification-mass spectrometry. Each protein module is a stable protein assembly whose subunit composition and interaction partners are characterised in a tissue-specific manner. The paper identifies modules that are ubiquitous across tissues alongside modules that are assembled or remodelled in tissue-specific patterns."

DEFS[434] = "Modules are not explicitly defined; the paper integrates barcoded neuroanatomy with spatial transcriptomics to link projection patterns to gene expression. Transcriptomically defined neuronal sub-types with characteristic projection patterns constitute functional circuit modules. The paper characterises how molecular identity (gene expression module) and connectivity (axonal projection module) are linked in individual neurons to define cell type-specific circuit modules."

DEFS[435] = "Modules are not explicitly defined; the paper proposes a path toward explainable AI inspired by biological neural networks. In the context of biological neural systems, functional modules — specialised brain regions performing defined cognitive operations — are the units that explainable AI architectures attempt to recapitulate. The paper discusses how modular neural network architectures inspired by brain organisation can improve the interpretability of AI systems."

DEFS[436] = "Modules are not explicitly defined; CeFra-seq reveals broad asymmetric distribution of mRNA and non-coding RNA across cellular fractions. Subcellular compartments (cytoplasm, mitochondria, ER, nucleus) constitute spatial modules that differentially contain specific RNA species. The paper characterises which RNA classes are enriched in which spatial modules, revealing RNA localisation as a layer of post-transcriptional gene expression organisation."

DEFS[437] = "Modules are not explicitly defined; the paper examines trans-synaptic signalling through the glutamate receptor delta-1. The glutamatergic synapse itself constitutes a modular signalling assembly: the presynaptic vesicle release machinery, postsynaptic receptor scaffold, and trans-synaptic adhesion complex constitute distinct functional modules that co-operate in excitatory synapse organisation and function. The paper characterises how GluD1 integrates with these synaptic modules."

DEFS[438] = "Modules are genetic circuit modules — defined gene regulatory circuits (toggle switch, repressilator) that can be combined within the AC-DC circuit framework. Each circuit module (toggle switch for bistable memory; repressilator for oscillation) has defined dynamical properties that are partially preserved upon combination. The paper examines how the combined circuit integrates the dynamical behaviours of its constituent modules and when module-level properties are retained or altered by circuit integration."

DEFS[439] = "Modules are protein complexes inferred from co-elution mass spectrometry data by the EPIC toolkit. Each predicted complex corresponds to a co-eluting protein group whose members show correlated elution profiles consistent with stable co-complex assembly. The module is defined by co-elution profile similarity and statistical evidence of co-complex formation, enabling proteome-scale mapping of protein complex modules in C. elegans."

DEFS[440] = "Modules are not explicitly defined; the paper examines sizer mechanisms controlling cell size. The cell size control regulatory module — comprising growth rate sensors, cell cycle cyclin-CDK complexes, and inhibitory factors (Wee1, CDK inhibitors) — constitutes a functional circuit measuring cell size and triggering division at a threshold. The paper characterises how this regulatory module implements sizer logic at different cell cycle checkpoints."

DEFS[441] = "Modules are morphological modules — semi-independent groups of cranial skeletal elements in caecilians whose shape variation and evolutionary trajectories are partially decoupled from one another. The paper characterises cranial modularity in caecilian amphibians, identifying which skull regions co-vary as modules and how modularity has changed across the caecilian evolutionary radiation. Modules are defined by within-module phenotypic integration exceeding between-module integration in geometric morphometric datasets."

DEFS[442] = "Modules are not explicitly defined; the paper describes bipartite graph convolutional networks for heterogeneous information fusion in drug-disease association prediction. Disease modules and drug modules in heterogeneous biomedical networks are the entities being linked. The paper uses graph convolution to learn module-level representations that capture the multi-relational context of drug-disease associations across different network layers."

DEFS[443] = "Modules are subgraphs — specific small connected patterns within larger networks whose frequency is counted. The paper surveys subgraph counting methods relevant to motif analysis and community detection in complex networks. In biological networks, over-represented subgraphs (motifs) constitute functional modules, and counting their occurrence provides statistical characterisation of modular network architecture."

DEFS[444] = "Modules are not explicitly defined; MultiMAGNA++ is a multiple network alignment method for aligning multiple protein interaction networks simultaneously. Conserved subgraphs identified by multi-network alignment correspond to evolutionarily conserved functional modules shared across multiple species. The paper evaluates alignment quality by comparing identified module correspondences to known orthologous protein complexes and functional annotations."

DEFS[445] = "Modules are not explicitly defined; the paper examines how archaeal cells share cell size control principles with bacteria despite noisier growth. The cell size control regulatory module — comprising growth rate sensors, cell cycle regulators, and division checkpoint proteins — constitutes a functional circuit that implements similar size-sensing logic across domains of life. The paper characterises how this regulatory module operates under higher noise in archaeal cells."
