# Definitions part 1: rows 65, 103-291
DEFS = {}

DEFS[65] = "A module (or 'nearly decomposable subsystem') is a semi-autonomous cluster of tightly interacting components whose interactions with other clusters are weak relative to internal interactions. Simon argues that near-decomposability is a universal property of complex systems arising from evolutionary and constructive pressures: hierarchical, modular organisation enables complex systems to be assembled and understood piece by piece. Modules are defined structurally by sparsity of cross-cluster interactions and functionally by semi-independent behaviour at the subsystem level."

DEFS[103] = "Modules are not the primary focus; the STRING database represents functional protein associations as a weighted network and implicitly treats densely connected subnetworks as functional modules. Protein clusters with high interaction confidence scores are treated as putative functional units whose members cooperate in shared biological processes or pathways. Module boundaries are operationalised through community detection algorithms applied to the weighted association graph."

DEFS[104] = "Modules are not explicitly defined; curated gene sets (pathways, ontology terms, co-expression signatures) serve as the functional units of interest. A gene set corresponds implicitly to a functional module: a group of genes sharing a common biological process, cellular location, or regulatory context. Enrichment analysis quantifies whether experimentally derived gene lists are enriched for membership in these predefined functional modules."

DEFS[105] = "Modules are implicitly defined as sets of proteins with high-confidence functional associations in the STRING network. The database integrates multiple evidence channels (co-expression, co-occurrence, text mining, experimental interaction, pathway co-membership) to score pairwise protein associations; dense subgraphs in the resulting network correspond to functional modules reflecting shared biological roles. Cluster detection algorithms extract discrete modules from the network for downstream pathway analysis."

DEFS[106] = "Modules are implicitly defined as co-regulated gene programs identified from single-cell transcriptional responses to CRISPR perturbations. The paper identifies coherent expression programs — groups of genes that respond similarly across multiple genetic perturbations — as functional regulatory modules. These modules link genetic perturbations to downstream transcriptional consequences and reveal the architecture of regulatory circuits at single-cell resolution."

DEFS[107] = "Modules are densely connected subsets of nodes in higher-order interaction networks (hypergraphs), where interactions can involve three or more nodes simultaneously. The paper extends standard graph-theoretic module concepts to hypergraph community structure, arguing that higher-order interactions define richer module boundaries than pairwise edges alone. Detection of such higher-order modules reveals functional groupings invisible to pairwise network analysis."

DEFS[108] = "Modules are not the explicit focus; the paper treats transcriptionally defined cell types as the fundamental organisational units of the cerebral cortex. Cell-type clusters identified by single-cell RNA-seq correspond to discrete functional modules of neural circuitry, characterised by shared gene expression programmes. Conserved cell types across species represent conserved modular units of cortical circuit architecture, while divergent features reflect species-specific elaborations of those modules."

DEFS[109] = "Modules are not explicitly defined; BioGRID provides a curated repository of genetic and protein interactions whose network representation supports downstream module detection. Dense subgraphs in the BioGRID interaction network correspond to protein complexes and functional modules — groups of proteins sharing interaction partners and cooperating in specific cellular processes. The database enables systematic identification of such modules across multiple organisms."

DEFS[110] = "Modules are disease modules: subnetworks of the human interactome in which disease-associated proteins cluster together within a localised network neighbourhood. The paper applies the network medicine framework where each disease corresponds to a network module defined by proximity of its associated proteins in the protein-protein interaction network. Drug targets and viral proteins are mapped onto this network to identify topological overlap between drug modules and disease modules as a proxy for therapeutic relevance."

DEFS[111] = "Modules are not explicitly defined; the paper maps spatially resolved transcriptomes of single cells in three-dimensional brain tissue. Distinct cell-type clusters identified by spatial transcriptomics correspond implicitly to functional modules of brain circuitry, characterised by unique gene expression profiles and anatomical locations. The spatial context adds a positional dimension to the definition of modular units within intact tissue architecture."

DEFS[112] = "Modules are not the explicit focus; the Harmonizome provides processed omics datasets that can be used to define gene and protein sets acting as functional modules. Gene sets derived from co-expression, pathway membership, or shared regulatory inputs implicitly define modules — groups of molecular entities coordinated in a common biological function. The database enables systematic identification and comparison of such module memberships across data types."

DEFS[113] = "Modules are protein communities — densely interconnected clusters within the human protein-protein interaction network identified by affinity purification-mass spectrometry. Each community corresponds to a set of proteins that preferentially associate with one another, reflecting shared complex membership or pathway co-participation. The BioPlex network supports hierarchical decomposition of the human proteome into nested modular communities at multiple scales."

DEFS[114] = "Modules are protein communities defined by the clustering structure of the human binary protein-protein interactome. Dense subgraphs in the interactome correspond to protein complexes and functional modules whose members share direct physical interactions. The paper uses network community detection to partition the interactome into modules and connects community structure to disease gene organisation and cellular function."

DEFS[115] = "Modules are not explicitly defined; BioGRID catalogs genetic and physical interactions that can be used to detect protein complexes and functional modules as dense subgraphs in the interaction network. The 2019 update expands multi-validated interaction datasets supporting identification of modular protein assemblies across organisms. Genetic interaction profiles additionally provide a complementary functional basis for grouping genes into modules sharing similar phenotypic consequences when perturbed."

DEFS[116] = "Modules are not explicitly defined; the paper profiles the mouse brain at single-cell resolution integrating molecular, spatial, and functional dimensions. Transcriptionally distinct cell-type clusters serve as functional modular units of brain circuitry. The spatial arrangement of these cell-type modules within anatomical brain regions provides a higher-order modular organisation linking molecular identity to circuit function."

DEFS[117] = "Modules are not the primary concept; the paper treats biological pathways as the functional units of interest. A pathway corresponds implicitly to a functional module: a coordinated set of molecular reactions and regulatory interactions performing a defined cellular function. Reactome pathway analysis tests whether experimentally derived gene lists are enriched for membership in these pathway modules, enabling systematic functional annotation."

DEFS[118] = "Modules are not explicitly defined; the paper treats curated gene sets (pathways, ontology terms, co-expression clusters) as functional modules for enrichment analysis. A functional module is a group of genes sharing a common biological process, molecular function, or regulatory context. WebGestalt tests whether experimentally derived gene lists are significantly enriched for members of these predefined functional modules."

DEFS[119] = "Modules are protein communities detected within the human binary protein-protein interactome constructed by systematic yeast two-hybrid screening. Dense subgraphs in the resulting network correspond to functional modules whose members share direct physical interactions. The reference interactome enables systematic mapping of disease gene modules — clusters of disease-associated proteins localised within the same network neighbourhood — to support network medicine analyses."

DEFS[120] = "Modules are not explicitly defined; the paper characterises the cellular composition and spatial architecture of cutaneous squamous cell carcinoma tumour tissue using multimodal single-cell analysis. Distinct cell-type clusters and spatially co-localised cell populations implicitly define functional modules of the tumour microenvironment — coordinated cellular units performing shared roles in tumour progression, immune evasion, or stromal support."

DEFS[121] = "Modules are not explicitly defined; the paper examines general principles governing the relationship between mRNA and protein abundances. Co-regulated sets of mRNAs and their protein products subject to shared translational or post-transcriptional control implicitly constitute functional modules. The study informs understanding of how gene expression modules are buffered or amplified at the translational level."

DEFS[122] = "Modules are not the primary framing; the paper studies the KRAS-RAF-MEK-ERK signalling pathway as an integrated functional unit whose disruption by the KRASG12C inhibitor MRTX849 has network-wide consequences. Downstream transcriptional and proteomic responses reveal adaptive reactivation of signalling modules. Pathway modules are implicitly defined by co-regulated expression changes and shared signal transduction roles within the MAPK network."

DEFS[123] = "Modules are not explicitly defined in the biological sense; GNN explanations identify subgraph patterns — small connected subgraphs or node clusters — important for model predictions. In biological applications such as molecular property prediction, these subgraph explanations correspond to functional moieties or protein interaction modules driving the predicted phenotype. The paper organises GNN explainability methods by how they define and extract these predictive subgraph units."

DEFS[124] = "Modules are communities of brain regions identified by network clustering of structural or functional connectivity data. In the context of brain communication dynamics, a module is a group of brain regions with denser within-module than between-module connectivity, enabling relatively independent signal routing. The paper examines how communication patterns across modules shape information flow and how module organisation relates to cognitive and behavioural functions."

DEFS[125] = "Modules are not explicitly defined; the paper frames the exposome in terms of molecular interaction networks linking chemical exposures to biological responses. Pathway and network modules represent clusters of molecular targets and biological processes through which chemical exposures converge to produce disease phenotypes. Network-based analysis of exposome data implicitly treats these pathway clusters as functional modules mediating environment-disease relationships."

DEFS[126] = "Modules are protein interaction communities — groups of proteins that co-assemble into distinct complexes or functional clusters detectable by co-fractionation mass spectrometry. The paper maps cell-specific protein interaction modules by comparing two cell-type-resolved proteome-scale networks, identifying modules that are stable across cell types alongside modules that are remodelled in a cell-type-specific manner. Each module corresponds to a protein complex or pathway unit with shared functional roles."

DEFS[127] = "Modules are not explicitly defined; the paper examines metabolic pathways supplying ATP to the brain and their failure in neurodegenerative disease. Metabolic pathway modules — such as glycolysis, oxidative phosphorylation, and the pentose phosphate pathway — are treated as coordinated functional units whose disruption contributes to neuronal energy deficits. The concept of energy rescue strategies implicitly targets these metabolic modules to restore energetic homeostasis."

DEFS[128] = "Modules are protein complexes; specifically, the m6A methyltransferase writer complex comprising METTL3, METTL14, WTAP, and associated factors including Zc3h13 constitutes a functional module for N6-methyladenosine deposition on nuclear RNA. Zc3h13 is shown to be required for the integrity and nuclear localisation of this writer complex module. The module is defined by co-complex membership and shared functional requirement for m6A methylation."

DEFS[129] = "Modules are not explicitly defined; the paper examines how the hypoxia-inducible factor (HIF) transcriptionally reprogrammes the glycolytic pathway module under hypoxic conditions. The glycolytic pathway and its regulatory connections to HIF constitute an integrated functional module coupling oxygen sensing to metabolic adaptation in cancer cells. The study characterises how this regulatory module is co-ordinately activated to shift energy metabolism from oxidative phosphorylation to glycolysis."

DEFS[130] = "Modules are not explicitly defined; miRNet maps miRNA-target interaction networks and supports identification of functional modules — clusters of miRNAs and their shared targets that co-regulate biological processes. A module in this context is a group of miRNAs whose target gene sets overlap substantially, suggesting coordinated regulation of a shared pathway or gene set. Network visualisation and enrichment analysis tools in miRNet enable identification of such regulatory modules."

DEFS[131] = "Modules are not explicitly defined; the MAPK signalling cascade (RAS-RAF-MEK-ERK) is treated as an integrated functional signalling module whose dysregulation drives cancer. Drug resistance mechanisms involve adaptive rewiring of this signalling module and its connections to parallel pathways. The paper implicitly treats individual pathway segments — receptor activation, MAPK cascade, transcriptional output — as functional sub-modules that can be independently or combinatorially targeted."

DEFS[132] = "Modules are not explicitly defined; the RAS-RAF-MAPK pathway is treated as a canonical signalling module whose oncogenic activation drives tumour progression. The paper reviews therapeutic strategies targeting distinct components of this signalling module and the adaptive responses that circumvent single-agent inhibition. Pathway segments — receptor tyrosine kinase activation, RAS GTPase cycling, RAF dimerisation, MEK-ERK cascade — function as sub-modules with partially separable therapeutic vulnerabilities."

DEFS[133] = "Modules are subnetworks of evolved neural networks that perform specific computational sub-tasks and arise through neuroevolution. The paper examines how neuroevolutionary algorithms produce neural architectures with modular organisation, where distinct subgraphs specialise for separable aspects of the overall task. Modularity in this context is both a structural property (sparse inter-module connectivity) and a functional one (specialisation of subnetwork computation)."

DEFS[134] = "Modules are not explicitly defined; the paper reviews how traditional Chinese medicine compounds interact with cancer-relevant molecular pathways. Signalling pathways and regulatory networks targeted by TCM compounds implicitly constitute functional modules whose perturbation mediates anti-tumour effects. Network pharmacology approaches used in this area treat pathway modules as the units of therapeutic action."

DEFS[135] = "Modules are not explicitly defined; the paper reviews molecular mechanisms of antifungal resistance in Candida species, focusing on drug efflux pumps, target enzyme modifications, and stress response pathways. These resistance mechanisms can be viewed as functional modules — coordinated sets of genes and proteins that collectively confer drug tolerance. The regulatory networks controlling resistance gene expression constitute higher-order modules linking stress sensing to adaptive transcriptional responses."

DEFS[136] = "Modules are not explicitly defined; the paper characterises the biogenesis, stability, and regulatory roles of circular RNAs in the context of cellular responses to stimulation. CircRNAs that sponge shared sets of microRNAs or interact with common RNA-binding proteins constitute functional regulatory modules. The paper's findings inform understanding of how circRNA-miRNA-mRNA regulatory modules are organised and dynamically regulated."

DEFS[137] = "Modules are not explicitly defined; the paper reviews how tea polyphenols interact with antioxidant defence pathways and molecular targets in human cells. The antioxidant response element (ARE)-Nrf2 pathway and related redox regulatory networks constitute functional modules whose activation by polyphenols mediates health-protective effects. Network pharmacology perspectives on tea polyphenol action implicitly treat these pathway modules as coordinated units of biological response."

DEFS[138] = "Modules are individual strand displacement reaction circuits or sub-circuits that can be designed, characterised, and composed in a modular fashion to build complex DNA-based molecular computation systems. Each module performs a defined input-output transformation (e.g., AND gate, threshold, amplifier) using toehold-mediated strand displacement as the underlying mechanism. The modular composability of these nucleic acid circuits enables hierarchical construction of complex computing systems from well-characterised parts."

DEFS[139] = "Modules are cell-type-specific functional modules — groups of proteins or genes that co-function in a specific tissue context. The paper integrates multi-layer tissue networks to predict protein functions in specific human tissues, treating tissue-specific network communities as functional modules whose membership is constrained by tissue expression patterns. A module in this framework is defined by the combination of interaction topology and tissue-specific co-expression."

DEFS[140] = "Modules are not explicitly defined; the paper analyses the genetic architecture of blood cell traits and diseases using genome-wide association studies. Gene sets associated with related blood cell phenotypes or sharing common regulatory loci implicitly constitute functional modules. Network analysis of GWAS results can reveal pathway modules in which multiple blood trait-associated variants converge on shared biological processes."

DEFS[141] = "Modules are not explicitly defined; the paper reviews the developmental origins and functional diversification of cortical GABAergic interneuron subtypes. Transcriptionally and functionally distinct interneuron classes serve as functional modules of cortical inhibitory circuits, each performing specialised roles in regulating network activity, timing, and gain control. The developmental programmes specifying each interneuron type constitute gene regulatory modules controlling module identity."

DEFS[142] = "Modules are communities of functionally connected brain regions identified from resting-state fMRI and structural connectivity data. The brain's modular organisation is characterised by dense within-module functional connectivity and sparse between-module connectivity, enabling both specialised local processing and distributed integration. The paper examines how modular and integrative aspects of brain network organisation relate to cognitive function and how these properties vary across individuals and brain states."

DEFS[143] = "Modules are protein co-regulation modules — groups of serum proteins whose abundances co-vary across individuals in a genetically correlated manner. These co-regulation modules reflect shared transcriptional or post-translational regulatory control and are identified by network-based analysis of proteomic data integrated with genetic association data. Each module links a cluster of serum proteins to shared genetic determinants and disease associations."

DEFS[144] = "Modules are protein complexes; the m6A mRNA methyltransferase writer complex comprising METTL3, METTL14, WTAP, and associated subunits including Zc3h13/Flacc constitutes a functional module for epitranscriptomic modification. Zc3h13/Flacc bridges the mRNA-binding subunit WTAP to the catalytic core, and its loss destabilises the entire complex module. The writer complex is thus defined as a biochemically discrete, functionally interdependent modular assembly."

DEFS[145] = "Modules are not explicitly defined; the paper reviews ionotropic and metabotropic glutamate receptor signalling systems in the CNS. The ionotropic (AMPA, NMDA, kainate) and metabotropic (mGluR) receptor families constitute distinct signalling modules coupled to different downstream effectors and performing complementary roles in synaptic transmission, plasticity, and neuroprotection. The paper characterises these receptor-signalling modules and their pharmacological manipulation."

DEFS[146] = "Modules are not the primary focus; the paper surveys link prediction methods for static and dynamic networks including biological interaction networks. Network community structure — groups of nodes with high internal connectivity — is used as one basis for link prediction: links within the same module are more likely than cross-module links. Module membership thus provides a structural prior for predicting missing or future edges in biological networks."

DEFS[147] = "Modules are not explicitly defined; Hsp90 and its co-chaperones constitute a modular chaperone machinery in which distinct co-chaperone modules regulate different aspects of client maturation. The paper describes how Hsp90 assembles into multi-protein chaperone complexes — involving Hsp70, Hop, p23, and other co-chaperones — that together control client protein folding, stability, and activity. Each co-chaperone sub-complex functions as a regulatory module of the overall Hsp90 machinery."

DEFS[148] = "Modules are disease modules — localised subnetworks of the human interactome in which proteins associated with a given disease cluster together. The network medicine framework identifies SARS-CoV-2 host interaction modules in the human interactome and tests topological proximity between these viral modules and the targets of approved drugs. A drug is predicted to be therapeutically relevant if its protein targets overlap with or are proximal to the disease or viral module in the interaction network."

DEFS[149] = "Modules are not the primary concept; the paper proposes a model-level explanation method for graph neural networks that identifies graph patterns maximally activating each GNN class. In biological graph applications, these explanatory subgraph patterns correspond to structural motifs or functional modules — small connected subgraphs whose presence strongly predicts a given molecular or phenotypic class. The paper defines these explanatory subgraphs structurally through generation-based optimisation."

DEFS[150] = "Modules are not explicitly defined; the EGFR signalling network is treated as an integrated functional module driving proliferation and survival in cancer cells. The paper reviews how EGFR activates downstream signalling modules (RAS-MAPK, PI3K-AKT, STAT) and how resistance arises through adaptive rewiring of these modules. Each downstream pathway constitutes a semi-independent signalling module that can be selectively targeted to overcome resistance."

DEFS[151] = "Modules are co-expressed protein modules — groups of proteins whose abundances co-vary across brain regions and disease stages — identified by weighted protein co-expression network analysis of multi-layer proteomic data. Each module corresponds to a coherent biological process (e.g., synaptic function, myelination, neuroinflammation) disrupted in Alzheimer's disease. Module preservation across independent cohorts and cross-species validation provides confidence in the biological relevance of each proteomic module."

DEFS[152] = "Modules are communities — groups of nodes in a network with denser internal than external connections. The paper surveys deep learning methods for community detection, treating communities as the structural modules of complex networks. In biological contexts, these communities correspond to functional modules such as protein complexes, co-expression clusters, or metabolic sub-networks. The survey organises methods by how they define and optimise community structure using neural network architectures."

DEFS[153] = "Modules are structural sub-assemblies of the mitochondrial respiratory megacomplex; the individual respiratory chain complexes (Complex I, III, IV) constitute discrete structural and functional modules that associate into supercomplexes and megacomplexes. Each complex module performs a defined electron transfer and proton translocation function, and their physical association enhances electron channelling efficiency. The paper characterises the stoichiometry and architecture of the I2III2IV2 megacomplex as a modular assembly."

DEFS[154] = "Modules are not explicitly defined; the paper describes an enhanced CRISPR-dCas9 repressor system for programmable gene regulation. The engineered repressor constitutes a functional module combining a DNA-targeting module (guide RNA plus dCas9) with a transcriptional repression effector module. Modular assembly of targeting and effector components enables flexible programming of gene regulatory modules in mammalian cells."

DEFS[155] = "Modules are communities in complex networks: groups of nodes with more connections to each other than to the rest of the network. The paper reviews community detection methods across disciplines, treating communities as the basic modular units of network organisation. In biological networks, such communities correspond to functional modules — protein complexes, regulatory circuits, co-expression clusters — whose dense internal connectivity reflects shared function or coordinated regulation."

DEFS[156] = "Modules are neuronal circuit elements — genetically defined cell types, projection pathways, and synaptic connections — whose roles in behaviour are dissected by targeted genetic tools. The paper reviews how genetic approaches enable identification and manipulation of discrete functional modules of neural circuits. Each genetically defined circuit element constitutes a module characterised by molecular identity, connectivity, and functional contribution to specific behaviours."

DEFS[157] = "Modules are not explicitly defined; TRRUST provides a curated reference of transcription factor-target gene interactions supporting reconstruction of transcriptional regulatory networks. Transcription factor regulons — the target gene sets controlled by a given transcription factor — implicitly define regulatory modules. Network analysis of TRRUST data enables identification of transcription factor modules that co-regulate shared gene sets and mediate coordinated transcriptional programmes."

DEFS[158] = "Modules are co-expression and co-abundance modules identified by network analysis of multi-omic data from Alzheimer's disease brain tissue. Each module corresponds to a group of molecular entities (transcripts or proteins) with correlated abundance profiles across samples, reflecting shared regulation or co-complex membership. Key modules dysregulated in Alzheimer's disease are identified by correlation of module eigengene expression with disease pathology and clinical variables."

DEFS[159] = "Modules are microbial co-occurrence clusters — groups of microbial taxa that co-occur more frequently with one another than expected by chance in microbial association networks. The paper provides tools for constructing and comparing such networks across conditions, with modules identified by community detection algorithms. A microbial module in this framework is defined structurally by the network topology and interpreted ecologically as a set of taxa sharing a niche or interacting closely."

DEFS[160] = "Modules are not explicitly defined; the antithetic integral feedback controller circuit constitutes a functional regulatory module achieving robust perfect adaptation in biomolecular networks. The circuit module consists of an actuator species and a sensor species whose interaction implements integral feedback. This two-component regulatory module is designed to function as a composable building block for achieving robust homeostasis in larger biochemical networks."

DEFS[161] = "Modules are hierarchically organised biological network substructures — groups of genes or proteins corresponding to known cellular subsystems (gene ontology terms, pathways, complexes) arranged in a hierarchy from genes to cells. The paper uses this biological hierarchy to constrain a deep neural network architecture, with each hidden neuron corresponding to a biological module. This allows the network to learn module-level representations interpretable in terms of known biological functions."

DEFS[162] = "Modules are not explicitly defined; the paper identifies KIF5A as a novel ALS risk gene through genome-wide association analysis. Kinesin motor proteins and their interaction partners in axonal transport networks implicitly constitute functional modules disrupted in ALS. The co-expression and interaction network context of KIF5A places it within a broader neuronal transport module whose dysregulation contributes to motor neuron degeneration."

DEFS[163] = "Modules are not explicitly defined; the RAS-RAF-MEK-ERK signalling cascade is treated as an integrated functional module, with ERK positioned as a central node whose inhibition can overcome resistance to upstream inhibitors. The paper argues that ERK is an 'Achilles heel' because it integrates multiple upstream signalling modules and cannot be bypassed. Individual pathway segments (receptor activation, RAS, RAF dimerisation, MEK, ERK) function as sub-modules with distinct but interconnected therapeutic roles."

DEFS[164] = "Modules are not explicitly defined; NLR (nucleotide-binding leucine-rich repeat) proteins constitute an immune receptor network in which pairs or groups of NLRs function as integrated modules for pathogen detection and immune activation. Sensor NLRs detect pathogen effectors and signal to helper NLRs in a defined module architecture. The paper examines how this NLR network modularity enables broad-spectrum immunity to diverse pathogens."

DEFS[165] = "Modules are not the primary concept; topologically associating domains (TADs) and CTCF-anchored loops constitute genomic regulatory modules — structurally defined chromatin units that bring enhancers and promoters into proximity to coordinate gene expression. The paper describes the structural basis for cohesin-CTCF interactions that anchor these loop modules. The cohesin-CTCF protein complex is the molecular module that demarcates genomic boundaries."

DEFS[166] = "Modules are subsets of species within an ecological community that interact more strongly with each other than with species in other modules. The paper examines the relationship between modularity — defined as the degree to which a food web or mutualistic network is partitioned into weakly coupled subgroups — and community stability. Modules are defined structurally by network community detection and interpreted ecologically as groups of species sharing habitats, trophic levels, or interaction partners."

DEFS[167] = "Modules are neuronal circuits — groups of anatomically and functionally connected neurons performing shared computational roles. In the context of the complete Drosophila connectome, modules are identified as densely interconnected neuronal subgraphs corresponding to known circuit functions (sensory processing, motor control, decision-making). The connectome enables systematic identification of modular circuit architecture at single-neuron resolution."

DEFS[168] = "Modules are microbial co-occurrence modules — groups of microbial taxa that co-occur more frequently with one another in plant-associated microbiomes at specific developmental stages. The paper characterises how plant developmental stage shapes the ecological roles and interaction patterns of microbial modules in the rhizosphere and phyllosphere. Module structure is identified by network community detection applied to 16S amplicon co-occurrence data."

DEFS[169] = "Modules are biomolecular feedback control circuits — specifically, integral feedback modules composed of a sensor/actuator pair that achieve robust perfect adaptation in the regulated molecular species. The universal integral controller module is designed to function as a composable regulatory building block that can be embedded in larger biochemical networks without requiring retuning. The module is defined by its input-output transfer function (integral action) and its biochemical implementation."

DEFS[170] = "Modules are microbial co-occurrence sub-networks — groups of diazotrophic (nitrogen-fixing) taxa that co-occur and potentially interact with one another across soil pH gradients. Network community detection identifies modules of co-occurring diazotrophs whose assembly and composition are shaped by soil pH as a key edaphic factor. Each module represents a putative ecological guild of co-occurring nitrogen fixers responding similarly to environmental gradients."

DEFS[171] = "Modules are not explicitly defined; the paper reviews how AI methods integrate molecular interaction networks to identify cancer targets and drug candidates. Pathway modules — clusters of co-expressed or co-interacting genes associated with cancer driver functions — serve as units of target identification. Network-based AI approaches identify modules whose perturbation is likely to have therapeutic effects, leveraging topological proximity within the cancer interactome."

DEFS[172] = "Modules are not the primary biological concept; the paper presents a unifying framework for quality-diversity optimisation algorithms in which behavioural descriptor spaces can be factored into modular dimensions. In applications to evolved or designed biological systems, modularity in the phenotype space corresponds to semi-independent trait dimensions that can be optimised separately. The framework treats modular decomposition of the solution space as a design choice enabling efficient exploration of diverse high-quality solutions."

DEFS[173] = "Modules are microbial co-occurrence modules — groups of bacteria and fungi in the wheat rhizosphere that exhibit strong co-occurrence patterns and form a less complex, more stable network compared to bulk soil. The paper identifies modules of co-occurring microbial taxa whose structure is shaped by plant root exudates and developmental stage. Module stability is assessed by comparing co-occurrence network topology across plant growth conditions."

DEFS[174] = "Modules are not explicitly defined; the paper characterises how distinct somatotopic regions and intensity-dependent neuronal circuits mediate acupuncture responses. Genetically defined neuronal populations and their projection targets constitute functional neural modules linking peripheral sensory input to central autonomic responses. The paper uses intersectional genetic tools to dissect the modular circuit architecture underlying acupuncture-induced physiological effects."

DEFS[175] = "Modules are not explicitly defined; the paper examines dynamic rewiring of signal transduction pathways in cancer cells in response to therapeutic perturbations. Signalling pathway segments (receptor activation, second messengers, kinase cascades, transcription factor activation) function as semi-independent modules that are dynamically reconfigured during drug resistance. The paper characterises how module interactions change over time under targeted therapy pressure."

DEFS[176] = "Modules are not explicitly defined; the paper examines coupled social-hydrological systems in the context of Sustainable Development Goals. In socio-ecological systems frameworks, functional modules correspond to semi-autonomous subsystems (e.g., water management institutions, ecological flow regimes, agricultural water use) that interact through defined coupling channels. The paper implicitly treats these coupled subsystems as modular units whose interactions determine the sustainability of the overall system."

DEFS[177] = "Modules are not the primary framing; the paper describes how digital evolution produces unexpected solutions to computational tasks. Evolving computational circuits that solve decomposable tasks often produce modular solutions where subnetworks specialise for sub-tasks. The paper's examples of digital evolution discovering novel solutions implicitly illustrate how modularity emerges when selection favours separable functional sub-circuits."

DEFS[178] = "Modules are genetic circuits — defined sets of genes and regulatory elements performing a specific input-output function — that are engineered to interact within and between synthetic minimal cells. The paper examines how modules composed of characterised genetic parts can be assembled and how interactions between modules affect circuit behaviour. Modularity is assessed by the degree to which a circuit's behaviour is preserved when interconnected with other circuits."

DEFS[179] = "Modules are not explicitly defined; the paper characterises how mechanotransduction activity in cochlear hair cells shapes the transcriptional identity and spontaneous activity of spiral ganglion neurons. Distinct neuronal subtypes identified by single-cell transcriptomics constitute functional modules of the auditory peripheral circuit. Gene expression programmes specifying each spiral ganglion neuron subtype represent transcriptional modules linking sensory activity to neuronal identity."

DEFS[180] = "Modules are not explicitly defined; the paper reviews how cell-cell communication networks coordinate multicellular function. Ligand-receptor interaction pairs and downstream signalling cascades constitute functional communication modules linking sender and receiver cells. The paper characterises how these communication modules are organised and dysregulated in disease, with implications for therapeutic targeting of intercellular signalling modules."

DEFS[181] = "Modules are co-expressed protein and RNA modules identified by weighted network analysis of integrated proteogenomic data from head and neck squamous cell carcinoma. Each module corresponds to a coherent set of molecular entities with correlated abundance profiles across tumours, reflecting shared regulation or pathway membership. Modules associated with clinical outcomes or treatment response provide mechanistic insight into tumour biology."

DEFS[182] = "Modules are functional groups of genes identified from genome-scale genetic interaction profiles in human cells. Genes whose knockout fitness profiles are highly correlated cluster into modules corresponding to shared complexes, pathways, or processes. The genetic interaction network is partitioned into hierarchical functional modules — from protein complexes to biological processes — enabling a systematic wiring diagram of human cell function."

DEFS[183] = "Modules are not explicitly defined as a primary concept; the paper reviews graph neural network methods applied to biomedical networks. Dense subgraphs or community structures in these networks correspond to functional modules (protein complexes, disease modules, cell-type clusters). GNN methods learn representations that capture module membership implicitly through neighbourhood aggregation, enabling prediction of module-level properties from network topology."

DEFS[184] = "Modules are not explicitly defined; the paper characterises the replicability of cell type definitions derived from single-cell RNA-seq clustering. Transcriptionally defined cell types constitute the fundamental functional modules of tissues, each characterised by a shared gene expression programme. The paper assesses how robustly these cell-type modules can be recovered across independent datasets, analytical methods, and biological replicates."

DEFS[185] = "Modules are not explicitly defined; the epithelial-mesenchymal transition (EMT) is treated as a regulatory module linking transcription factor networks to metabolic reprogramming in cancer cells. EMT transcription factors (ZEB1/2, SNAI1/2, TWIST) and their downstream metabolic targets constitute a coupled regulatory-metabolic module driving cancer invasion and metastasis. The paper characterises how EMT regulatory modules are coupled to shifts in oxidative, glycolytic, and lipid metabolic sub-modules."

DEFS[186] = "Modules are not explicitly defined; the paper examines how APOE4 disrupts intracellular lipid homeostasis in glial cells. Lipid metabolic pathways and membrane phospholipid biosynthesis constitute functional metabolic modules that are perturbed by APOE4. The paper identifies shared lipid homeostasis module dysfunction across human iPSC-derived glia and yeast APOE4 models, suggesting conserved molecular mechanisms."

DEFS[187] = "Modules are not explicitly defined; WebGestalt treats curated gene sets (pathways, gene ontology terms, co-expression clusters) as functional modules for enrichment analysis. The 2024 update extends module-based analysis to metabolomics data, enabling enrichment testing for metabolic pathway modules. A functional module is a group of genes or metabolites sharing a common biological process or metabolic pathway."

DEFS[188] = "Modules are not explicitly defined; the paper reviews principles governing locomotion across physical scales and substrates. Locomotor systems in animals can be conceptualised as modular, with distinct sub-systems (central pattern generators, limb mechanics, sensory feedback) constituting functional modules whose interactions produce coordinated movement. Robophysics examines how module interactions enable robust locomotion across diverse environments."

DEFS[189] = "Modules are protein complexes; the m6A methyltransferase writer complex and the Xist-associated regulatory machinery constitute functional modules for X-chromosome inactivation. The paper identifies Rbm15, Spen, and Wtap as components of overlapping protein modules linking m6A deposition to Xist-mediated transcriptional silencing. Each module is defined by co-complex membership and shared functional requirement in XCI."

DEFS[190] = "Modules are metabolic pathway modules — groups of enzymatic reactions performing defined biosynthetic or catabolic functions within a genome-scale metabolic model. gapseq identifies pathway completeness by assessing which enzymatic modules can be assembled from genomic evidence, then fills gaps to produce complete modular metabolic reconstructions. Each pathway module is defined by its reaction membership and stoichiometric connectivity within the metabolic network."

DEFS[191] = "Modules are not explicitly defined; the paper uses genome-wide CRISPR screens in 3D spheroid cancer models to identify genes essential for growth in a three-dimensional tumour-like context. Gene sets required specifically for 3D growth implicitly define functional modules supporting tumour architecture, cell-cell adhesion, or microenvironmental adaptation. Pathway analysis of 3D-specific essentials reveals the functional modules uniquely required in tumour-relevant growth conditions."

DEFS[192] = "Modules are not explicitly defined; the paper characterises the complete proteome of E. coli under diverse growth conditions, mapping protein expression to known cellular processes and pathways. Functionally coherent groups of co-regulated proteins — operons, metabolic pathways, molecular machines — constitute functional modules whose expression is coordinated in response to growth conditions. The proteome landscape reveals which functional modules are constitutive versus conditionally expressed."

DEFS[193] = "Modules are not explicitly defined; the paper examines enrichment analysis tools for gene set analysis in multi-omics contexts. Gene sets derived from pathways, ontologies, or co-expression analyses implicitly define functional modules. The paper evaluates how choice of pathway database and statistical method affects identification of significantly enriched modules in omics data."

DEFS[194] = "Modules are functional groups of genes identified by analysing yeast whole-genome duplicate gene retention and synthetic interactions. Duplicate gene pairs that are retained often participate in functional modules where partial redundancy buffers module function. The paper examines how genetic interactions between duplicated genes reveal the modular architecture of the yeast genetic network."

DEFS[195] = "Modules are not explicitly defined; the paper reviews link prediction methods applied to drug-target interaction networks and protein-protein interaction networks. Network community structure — groups of topologically similar nodes — provides a basis for predicting new drug-target links within functional modules. Module membership is an implicit feature used by many link prediction algorithms to identify candidate drug-target associations."

DEFS[196] = "Modules are co-expressed protein modules — groups of proteins whose abundances co-vary across Alzheimer's disease brain samples and map to defined biological processes. The paper uses systems-level proteomics and network analysis to identify modules disrupted across AD stages, connecting molecular module dysfunction to clinical disease progression. Each module corresponds to a coherent biological sub-system (synaptic, metabolic, immune) implicated in AD pathology."

DEFS[197] = "Modules are not explicitly defined; the paper studies selenoprotein translation and ferroptosis. The selenoprotein synthesis machinery — including the SECIS element, SECISBP2, EFSec, and the ribosome — constitutes a functional translation module for selenocysteine incorporation. The paper identifies how stalling of this specialised translation module during ferroptosis-relevant conditions exposes a vulnerability in redox homeostasis."

DEFS[198] = "Modules are not explicitly defined; the kinase interaction network (KIN) maps physical and functional interactions among human kinases and their substrates. Densely connected kinase clusters in this network constitute functional signalling modules performing related phosphorylation-dependent regulatory roles. The paper expands the functional annotation of the human kinome by identifying disease-relevant kinase modules and their interaction partners."

DEFS[199] = "Modules are not explicitly defined; the paper maps the functional proteome of E. coli at genome scale, assigning proteins to functional categories and molecular machines. Protein complexes and metabolic pathway assemblies constitute the functional modules of E. coli, each characterised by defined subunit composition and cellular role. The proteome landscape reveals the modular organisation of E. coli cellular processes from molecular machines to metabolic networks."

DEFS[200] = "Modules are not explicitly defined; the paper reviews tools for integrating, visualising, and analysing genomics data through biological networks. Pathway modules and protein interaction communities serve as the units of biological interpretation for omics data. Network-based tools enable identification of enriched or perturbed modules from high-throughput datasets."

DEFS[201] = "Modules are not explicitly defined; the paper examines how time perception changes with ageing using Bayesian optimisation and neural network models. In the context of brain network ageing, functional modules — communities of brain regions with correlated activity — are implicitly treated as units whose within-module connectivity and between-module communication change with age. The paper connects age-related changes in neural network architecture to cognitive timing performance."

DEFS[202] = "Modules are not explicitly defined; the paper characterises the structure, dynamics, and architecture of the nuclear pore complex (NPC). The NPC itself is a modular macromolecular assembly composed of distinct sub-complexes (scaffold nucleoporins, FG-nucleoporins, transport factor docking sites) each constituting a functional module. The paper addresses how FG-repeat nucleoporins stabilise the NPC structure and contribute to the selective transport module."

DEFS[203] = "Modules are protein complexes; specifically, the paper examines how long non-coding RNAs act as scaffolds that organise protein complexes into functional modules. lncRNAs that bridge multiple protein interaction partners constitute structural scaffolding modules bringing enzymatic activities into spatial proximity. The paper predicts that protein complex scaffolding is a prevalent function of lncRNAs, defining a class of RNA-based organisational modules."

DEFS[204] = "Modules are functionally defined gene sets constituting a maternal functional module — a group of genes whose products are maternally deposited in the oocyte and collectively required for successful oocyte-to-embryo transition. The paper identifies the composition and regulation of this maternal module, characterising its role in early embryonic development before zygotic genome activation. The module is defined by shared temporal expression and functional requirement in the earliest developmental stage."

DEFS[205] = "Modules are functional communities of brain regions — groups of brain areas with high co-activation during specific cognitive tasks that form modules in dynamic functional connectivity networks. The paper tracks how functional brain modules reorganise as cognitive demands increase, with more modular (segregated) networks during demanding tasks and more integrated networks during rest. Module boundaries are defined by temporal correlation patterns in functional MRI data."

DEFS[206] = "Modules are protein complexes; specifically, the COMMD/CCDC22/CCDC93 (CCC) complex constitutes a functional module for endosomal recycling that regulates phosphoinositide composition on endosomal membranes. The CCC complex module coordinates with other endosomal coat complexes (WASH, retriever) to sort cargo proteins. The module is defined by stable co-complex membership and shared functional requirement in endosomal PI(3)P regulation."

DEFS[207] = "Modules are not explicitly defined; the paper addresses host-aware synthetic biology — designing genetic circuits that account for the host cell context in which they operate. Genetic circuit modules are functional units (promoters, regulatory elements, gene cassettes) whose behaviour depends on host cellular resources. The paper examines how module performance is affected by host state (growth rate, metabolic load) and how host-awareness can be incorporated into modular circuit design."

DEFS[208] = "Modules are not explicitly defined; the paper describes a deep learning framework for protein function prediction using network-based features. Protein interaction modules — groups of proteins with shared network topology — implicitly provide functional context for prediction. The framework integrates network module membership with sequence features to improve function prediction accuracy."

DEFS[209] = "Modules are not explicitly defined; the paper analyses properties of bacterial protein interaction networks, including clustering, modularity, and small-world features. Dense subgraphs in bacterial protein networks correspond to protein complexes and functional modules performing defined cellular roles. The paper characterises how modular network organisation relates to gene co-expression, operon structure, and functional annotation."

DEFS[210] = "Modules are not explicitly defined; the paper presents a topology potential-based method for identifying essential proteins from protein-protein interaction networks. Highly connected nodes that anchor network modules (hub proteins within dense subgraphs) are predicted to be essential. The method uses the topological importance of proteins within their local network modules as a proxy for essentiality."

DEFS[211] = "Modules are not explicitly defined; the paper studies how METTL3 acetylation regulates its nuclear activity and cancer metastasis. The m6A methyltransferase complex — METTL3, METTL14, WTAP, and associated factors — constitutes a functional writer module whose localisation and activity are modulated by post-translational modification. The paper characterises how acetylation fine-tunes module activity to control cancer-relevant gene expression programmes."

DEFS[212] = "Modules are not explicitly defined; the paper studies how Rab5 and the ALS-related protein Alsin regulate cytoprotective signalling on mitochondria-associated membranes. Rab5-positive endosomal membranes and their associated regulatory proteins constitute a functional module for stress signalling at the endosome-mitochondria interface. The module is defined by spatial co-localisation and shared functional requirement in stress response."

DEFS[213] = "Modules are not explicitly defined; the paper tracks longitudinal changes in cortical functional organisation in patients with multiple sclerosis. Functionally defined brain modules — communities of brain regions with correlated activity — are used as units of analysis to characterise how cortical reorganisation compensates for structural damage. Changes in within-module and between-module functional connectivity serve as biomarkers of disease progression and adaptive plasticity."

DEFS[214] = "Modules are not explicitly defined; the paper studies how EBV miRNA-BART8-3p induces EMT and promotes gastric cancer metastasis. The epithelial-mesenchymal transition regulatory module — comprising EMT transcription factors, their targets, and upstream miRNA regulators — is co-ordinately activated by the viral miRNA. The paper characterises how viral miRNA reprogramming of this regulatory module drives cancer progression."

DEFS[215] = "Modules are transcriptional regulatory modules — groups of transcription factors and their co-regulated target genes controlling vascular cambium development in plants. The paper constructs a transcriptional regulatory framework for cambium development by identifying co-expressed gene modules and their upstream regulators. Each module corresponds to a regulatory programme active at a specific stage of cambial cell differentiation."

DEFS[216] = "Modules are densely connected subgraphs in biological networks identified by higher-order clustering methods. The paper proposes HiSCF, a method that leverages higher-order structural patterns (network motifs, simplicial complexes) to identify biologically meaningful modules. In protein interaction networks, modules detected by HiSCF correspond to protein complexes and functional sub-networks that share higher-order topological patterns beyond simple pairwise connectivity."

DEFS[217] = "Modules are morphological modules — semi-independent anatomical trait groups that co-vary within but not between modules across species. The paper evaluates statistical methods for detecting modular signal in morphological trait matrices, comparing the strength and robustness of module detection across phylogenetic comparative methods. Modules are defined by within-module phenotypic covariation exceeding between-module covariation in a population or phylogenetic context."

DEFS[218] = "Modules are not explicitly defined; the paper characterises tricalbins as ER-plasma membrane contact site tethers that facilitate lipid transfer. The tethering complex at ER-PM contact sites — comprising tricalbins and associated proteins — constitutes a functional lipid transfer module. The module is defined by its co-localisation at contact sites and shared functional requirement for phospholipid flux between organelle membranes."

DEFS[219] = "Modules are gene co-expression modules identified by network analysis of expression data across species. The paper examines the evolutionary origins of co-expression modules by phylogenomic analysis, asking which modules are conserved across deep evolutionary time versus lineage-specific. Co-expression module conservation is used as evidence of shared functional coordination and evolutionary constraint on gene regulatory programmes."

DEFS[220] = "Modules are not explicitly defined; the paper reviews network neuroscience perspectives on human learning, examining how brain network organisation supports acquisition of new knowledge and skills. Functional brain modules — communities of co-activating brain regions — are the units of analysis for tracking learning-induced changes in network architecture. The paper discusses how modular network properties (flexibility, integration) predict individual differences in learning."

DEFS[221] = "Modules are structural sub-complexes of the condensin complex; the paper characterises cryo-EM structures of condensin revealing a subunit arrangement in which the SMC heterodimer, kleisin, and HEAT repeat subunits constitute distinct structural and functional modules. The ATP-dependent conformational cycle of condensin involves coordinated movements of these modular sub-assemblies. Each module is defined by stable co-complex membership and distinct functional contribution to DNA looping."

DEFS[222] = "Modules are microbial community assemblages in plastisphere biofilms — groups of co-occurring microbial taxa that form distinct communities on plastic debris in freshwater wetlands. The paper characterises biofilm formation, community structure, and functional potential in these modules. Module membership is determined by co-occurrence network analysis of 16S amplicon data from plastic-associated microbiomes."

DEFS[223] = "Modules are not explicitly defined; the paper describes genome-scale metabolic network reconstruction for model animals and their application to predicting metabolic phenotypes. Metabolic pathways within the reconstructed models constitute modular functional units — groups of reactions performing defined biosynthetic or catabolic functions. The paper uses modular metabolic network analysis to predict and understand animal metabolic physiology."

DEFS[224] = "Modules are not explicitly defined; the paper examines mechanisms of mutational robustness in transcriptional regulation, focusing on how redundancy in regulatory networks buffers against mutations. Transcriptional regulatory modules — groups of transcription factor binding sites or co-regulators controlling shared target genes — provide robustness through within-module redundancy. The paper characterises how module structure influences the phenotypic consequences of regulatory mutations."

DEFS[225] = "Modules are modular components of artificial neural networks — separable sub-networks or layers with distinct computational roles that can be independently trained, transferred, or reused. The paper reviews modularisation techniques including mixture-of-experts, capsule networks, and slot-based architectures. In the context of biological applications, modular neural network components correspond to domain-specific processing units analogous to functional modules in biological systems."

DEFS[226] = "Modules are not explicitly defined; the paper characterises how ZMYND8 co-localises with the NuRD chromatin remodelling complex at target genes and regulates transcription through Poly(ADP-Ribose) polymerase activity. The NuRD complex and ZMYND8 together constitute a co-regulatory module at specific genomic loci. The module is defined by stable protein co-complex membership and shared functional requirement for target gene regulation."

DEFS[227] = "Modules are not explicitly defined; the paper reviews how traditional ethnopharmacology informs modern natural drug discovery. Bioactive compounds from natural sources interact with disease-relevant molecular pathway modules — signalling cascades, metabolic pathways, protein complexes — to produce therapeutic effects. Network pharmacology approaches map the interactions between natural compounds and these pathway modules to identify targets and mechanisms."

DEFS[228] = "Modules are not explicitly defined; the paper describes MAGE multiplex genome engineering in yeast. The gene editing machinery and its chromosomal targets constitute functional modules for metabolic engineering applications. Sets of co-edited genes targeting a shared metabolic pathway implicitly define modular editing targets whose collective modification achieves a desired phenotypic outcome."

DEFS[229] = "Modules are protein complexes detected by structural proteomics in a thermophilic organism. The paper uses systematic cross-linking mass spectrometry to map protein interaction communities — groups of proteins that stably co-purify and share interaction interfaces — as the fundamental modular units of cellular organisation. Each detected protein community corresponds to a functional module performing a defined role in the thermophilic cell."

DEFS[230] = "Modules are not explicitly defined; the paper examines multifunctional soft machines based on stimuli-responsive hydrogels. In the context of engineered biological-inspired systems, modular design involves combining gel components with distinct stimuli-response properties into composite devices. Each stimuli-responsive component constitutes a functional module whose independent operation enables multi-modal device behaviour."

DEFS[231] = "Modules are not explicitly defined; the paper identifies extreme multifunctional (moonlighting) proteins in the human protein interaction network. Moonlighting proteins participate in multiple distinct functional modules simultaneously — they are shared components at the intersection of different network communities. The paper uses network topology to characterise how such multi-module membership relates to protein essentiality and disease association."

DEFS[232] = "Modules are multienzyme complexes — groups of metabolic enzymes that physically co-localise in living cells to perform sequential reactions in glucose metabolism. The paper identifies a metabolic module in which glycolytic enzymes assemble into a metabolon complex for channelled glucose catabolism. The module is defined by direct protein-protein interactions and co-localisation of enzymes catalysing sequential metabolic steps."

DEFS[233] = "Modules are not explicitly defined; the paper reviews clinical metabolomics for inborn errors of metabolism. Metabolic pathway modules — groups of enzymatic reactions performing defined biosynthetic or catabolic functions — are the units disrupted in inborn errors of metabolism. Clinical metabolomics identifies diagnostic biomarkers reflecting the specific metabolic module affected by each enzyme deficiency."

DEFS[234] = "Modules are not explicitly defined; the paper examines nonlinear delay differential equation models of biological regulatory systems. Feedback loops and regulatory circuits in gene networks and signalling cascades constitute the modular units of analysis. Each circuit motif (negative feedback loop, positive feedback loop, incoherent feedforward) is a functional module whose delay and nonlinearity determine its dynamical behaviour."

DEFS[235] = "Modules are not explicitly defined; the paper presents a phylogenetic method for comparing evolutionary rates across morphological trait matrices. In the context of morphological evolution, modules are semi-independent trait groups whose rates of evolution can diverge. The paper provides statistical tools for testing whether trait sub-groups evolve at distinct rates, enabling inference of evolutionary module boundaries."

DEFS[236] = "Modules are protein complexes predicted by AI-assisted structural proteomics. The paper combines AlphaFold protein structure predictions with co-fractionation mass spectrometry data to identify stable protein complexes — functional modules defined by structural complementarity and physical co-association. Each predicted complex corresponds to a modular assembly whose subunit composition and architecture are inferred computationally."

DEFS[237] = "Modules are not explicitly defined; the paper describes genome assembly improvement and mapping of convergently evolved skeletal traits in stickleback fish. Skeletal morphological modules — anatomically semi-independent trait groups (e.g., pelvic girdle, armour plates, jaw) — are the units of convergent evolutionary change. The paper maps genetic loci controlling these morphological modules across independent marine-freshwater transitions."

DEFS[238] = "Modules are not explicitly defined; the paper examines strengths and weaknesses of deep neural networks for visual recognition. In the context of computational models of visual processing, modular sub-networks (e.g., edge detection, object recognition, spatial reasoning) correspond to functional modules of the visual system. The paper discusses whether current deep networks recapitulate the modular functional architecture of biological visual cortex."

DEFS[239] = "Modules are not explicitly defined; the paper examines HDAC6 as a therapeutic target in Charcot-Marie-Tooth disease caused by mutant GARS. The axonal transport machinery — kinesins, dynein, associated regulatory proteins — constitutes a functional module whose dysfunction underlies axonal neuropathy. HDAC6 inhibition rescues axonal transport module function. The module is implicitly defined by shared contribution to axonal cytoskeletal dynamics."

DEFS[240] = "Modules are not explicitly defined; the paper reviews extracellular NAMPT as a cancer metabolic target. The NAD+ biosynthesis pathway constitutes a functional metabolic module whose components are co-ordinately regulated in cancer cells. The paper characterises how the extracellular NAMPT module contributes to tumour cell survival and examines its potential as a therapeutic target within the broader metabolic reprogramming landscape of cancer."

DEFS[241] = "Modules are plant functional trait modules — semi-independent groups of traits that co-vary across environmental gradients and growth conditions due to shared underlying physiology or evolutionary constraints. The paper examines how trait connection patterns within and between modules remain stable (robust) versus change across environments. Modules are defined by statistical co-variation in trait space and interpreted as reflecting integrated functional strategies."

DEFS[242] = "Modules are not explicitly defined; the paper describes real-time imaging of single-molecule enzyme cascades on DNA origami scaffolds. Enzyme pairs tethered on DNA origami scaffolds constitute a functional module in which substrate channelling between co-localised enzymes improves cascade efficiency. The scaffold module is defined by spatial co-localisation and functional cooperativity of sequentially acting enzymes."

DEFS[243] = "Modules are not explicitly defined; the paper reviews anti-ageing strategies for neurodegenerative diseases. Molecular mechanisms of neurodegeneration — protein aggregation, mitochondrial dysfunction, neuroinflammation, synaptic loss — constitute functional modules whose dysregulation drives disease progression. The paper characterises how targeting individual modules or their interactions can slow neurodegeneration and extend healthspan."

DEFS[244] = "Modules are not explicitly defined; the paper examines decision-making from an ecological and subjective perspective in animals. In the context of neural decision-making, brain circuit modules — defined groups of neurons mediating specific decision components (value computation, comparison, commitment) — constitute the functional units of analysis. The paper bridges ecological decision-making theory with neural circuit module organisation."

DEFS[245] = "Modules are transcriptomically defined cell clusters — groups of neurons with shared gene expression profiles constituting distinct cell-type modules within the Drosophila circadian neuron network. The paper constructs a transcriptomic taxonomy of clock neurons, identifying modules of neurons with shared molecular identity and potentially shared circuit functions. The taxonomy defines the modular cellular composition of the circadian pacemaker circuit."

DEFS[246] = "Modules are not explicitly defined; the paper studies FG-nucleoporin repeat domains that form the selective transport barrier of the nuclear pore complex. The FG-nucleoporin module — a collective of intrinsically disordered repeat-containing proteins lining the NPC central channel — constitutes a functional module for nucleocytoplasmic transport selectivity. The module is defined by shared protein architecture, co-localisation within the NPC, and collective contribution to transport barrier function."

DEFS[247] = "Modules are not explicitly defined; the paper uses evolutionary proteomics to uncover ancient associations between cilia and signalling pathways. The ciliary proteome constitutes a functional module — a coherent set of proteins co-evolved for cilium assembly, maintenance, and signalling. The paper identifies conserved signalling pathway modules ancestrally associated with cilia, predating metazoan origins."

DEFS[248] = "Modules are not explicitly defined; the paper reviews clinical pharmacology of reactive oxygen species (ROS). Redox regulatory modules — sets of enzymes, antioxidants, and signalling mediators that collectively control ROS levels — constitute functional units whose perturbation underlies many diseases. The paper characterises how pharmacological intervention in these redox modules can be harnessed therapeutically."

DEFS[249] = "Modules are co-expression modules identified by multi-scale network analysis in independent Alzheimer's disease cohorts. The paper reports that the same molecular modules are disrupted across cohorts, providing robust evidence for a core set of affected biological processes. Each module corresponds to a group of genes or proteins with correlated expression that maps to a specific biological sub-system relevant to AD pathology."

DEFS[250] = "Modules are not explicitly defined; the paper reviews data-independent acquisition (DIA) proteomics methodology. Protein complexes and co-regulated protein sets identified from DIA data constitute functional modules of the proteome. The paper provides guidelines for accurate quantification of protein modules across conditions using DIA-based workflows."

DEFS[251] = "Modules are morphological modules — semi-independent groups of skeletal and developmental traits that exhibit coherent evolutionary trajectories. The paper examines how morphological development constrains and guides evolutionary change by linking developmental programmes to phenotypic modules. Developmental constraints on module variation determine the directions of accessible evolutionary change in morphological space."

DEFS[252] = "Modules are not explicitly defined; the paper analyses genomic determinants of protein abundance variation in colorectal cancer using proteogenomic approaches. Co-regulated protein sets controlled by shared genomic alterations (copy number variation, mutations) constitute expression modules. The paper characterises how cancer-specific genomic events perturb specific protein abundance modules to drive tumour phenotypes."

DEFS[253] = "Modules are not explicitly defined; the paper reviews novel CDK regulatory mechanisms and their therapeutic implications in cancer. The cyclin-CDK regulatory complexes that control cell cycle progression constitute functional modules — protein complexes whose activity is regulated by cyclin binding, CDK inhibitors, and phosphorylation. The paper characterises how different CDK module compositions determine substrate specificity and cell cycle phase transitions."

DEFS[254] = "Modules are genetic interaction modules — groups of genes linked by complex genetic interactions (both negative and positive) that reflect shared pathway membership or compensatory relationships. The paper examines whole-genome duplicate gene retention and the complex genetic interactions that arise between paralogous genes. These interaction modules reveal functional redundancy and compensation within the yeast gene network."

DEFS[255] = "Modules are not explicitly defined; the paper surveys network link prediction methods applied to drug discovery networks. Protein complexes and pathway modules in drug-target interaction networks are implicitly treated as units of analysis: links predicted within the same module are more likely to represent true drug-target interactions. The paper reviews how network module properties inform link prediction performance."

DEFS[256] = "Modules are protein co-expression and co-interaction modules identified by network analysis of multi-layer Alzheimer's disease brain proteomics data. Each module corresponds to a group of proteins with correlated abundances across brain regions and disease stages, reflecting shared regulation, complex membership, or pathway co-participation. The paper identifies AD-associated modules and validates them across independent cohorts."

DEFS[257] = "Modules are not explicitly defined; the paper examines how ribosome stalling during selenoprotein translation exposes ferroptosis vulnerability. The selenoprotein synthesis machinery constitutes a specialised functional module for selenocysteine incorporation. The paper characterises how stalling of this translation module under cellular stress conditions connects selenoprotein synthesis to ferroptosis regulation."

DEFS[258] = "Modules are functional kinase groups — clusters of kinases with shared interaction partners, substrates, or cellular roles. The kinase interaction network (KIN) partitions the human kinome into functional modules by interaction profile similarity. The paper expands kinase module annotations by mapping physical and genetic interactions, enabling identification of disease-relevant kinase modules and their functional roles."

DEFS[259] = "Modules are not explicitly defined; the paper maps the functional proteome landscape of E. coli across growth conditions. Operons, metabolic pathways, and molecular machines constitute the functional modules of E. coli, each characterised by coordinated protein expression and defined cellular role. The proteome landscape reveals which functional modules are expressed constitutively versus conditionally across diverse environmental conditions."

DEFS[260] = "Modules are not explicitly defined; the paper reviews network-based approaches for integrating and visualising genomics data in biological pathway context. Biological pathways and gene ontology functional groups serve as predefined modules for enrichment analysis. The paper describes how these reference modules enable biological interpretation of high-throughput genomics datasets through network visualisation."

DEFS[261] = "Modules are not explicitly defined; the paper examines age and cognitive effects on time perception using Bayesian computational models. In the context of neural network ageing, functional brain modules — communities of brain regions mediating temporal processing — are implicitly units whose dynamics change with age. The paper connects model parameters for time perception to neural network module properties."

DEFS[262] = "Modules are not explicitly defined; the paper characterises the nuclear pore complex structure, dynamics, and architecture. The NPC is a modular macromolecular assembly composed of distinct sub-complexes (scaffold, linker, FG-nucleoporins) each constituting a functional module with defined architectural roles. The paper examines how these structural modules interact to maintain NPC integrity and transport function."

DEFS[263] = "Modules are protein complexes; the paper examines how long non-coding RNAs scaffold protein assemblies. lncRNAs that simultaneously bind multiple protein interaction partners constitute structural scaffolding modules that co-ordinate the assembly of functional protein complexes. The paper predicts that protein complex scaffolding is a widespread lncRNA function, defining a class of RNA-based organisational modules at specific genomic loci."

DEFS[264] = "Modules are functionally defined gene sets constituting maternal functional modules — groups of maternally deposited gene products collectively required for successful oocyte-to-embryo transition in mammals. The paper identifies the composition and regulation of this maternal module, characterising its role in early embryonic development before zygotic genome activation. The module is defined by temporal co-expression in oocytes and shared functional requirement."

DEFS[265] = "Modules are functional communities of brain regions with high co-activation during cognitive tasks in dynamic functional connectivity networks. The paper tracks how brain functional modules reorganise as cognitive demands increase, examining the transition between segregated (modular) and integrated network states. Module boundaries are defined by temporal correlation patterns in functional MRI data, and module flexibility predicts cognitive performance."

DEFS[266] = "Modules are protein complexes; the COMMD/CCDC22/CCDC93 (CCC) complex constitutes a functional module for endosomal recycling. The CCC complex module coordinates with WASH and retriever complexes to sort cargo proteins from endosomes to the cell surface. The module is defined by stable co-complex membership and shared functional requirement for endosomal PI(3)P regulation and cargo recycling."

DEFS[267] = "Modules are not explicitly defined; the paper addresses host-aware synthetic biology and the challenges of designing genetic circuits that function reliably within living cells. Genetic circuit modules — functional units composed of promoters, regulatory elements, and gene cassettes — interact with host cellular resources (ribosomes, RNA polymerases, metabolites). The paper examines how host-circuit module interactions cause context-dependent behaviour and how host-awareness improves module design."

DEFS[268] = "Modules are not explicitly defined; the paper describes a deep learning framework (DeepFunc) for protein function prediction. Protein interaction modules — groups of proteins with shared network neighbourhood — provide functional context that improves prediction accuracy. The framework integrates module membership with sequence features to predict protein function categories from the GO hierarchy."

DEFS[269] = "Modules are functional groups in bacterial protein interaction networks — densely connected sub-networks corresponding to protein complexes and metabolic pathways. The paper analyses properties of bacterial protein networks, including modularity scores, hub connectivity, and module composition. Modules are defined structurally by network clustering and interpreted functionally by overlap with known metabolic pathways and gene regulatory units."

DEFS[270] = "Modules are not explicitly defined; the paper presents a topology-potential method for identifying essential proteins. Hub nodes that anchor dense network communities (modules) are predicted to be essential because their removal would destabilise the module and disrupt multiple functional processes simultaneously. The method uses the network topological importance of proteins within their local modules as an essentiality proxy."

DEFS[271] = "Modules are not explicitly defined; the paper studies how METTL3 acetylation at specific residues impedes its nuclear retention and cancer metastasis. The nuclear m6A methyltransferase complex module — METTL3, METTL14, WTAP, and their nuclear interaction partners — is regulated by post-translational modification. The paper characterises how acetylation fine-tunes module nuclear activity to control metastasis-relevant transcriptional programmes."

DEFS[272] = "Modules are not explicitly defined; the paper studies Rab5 and Alsin in stress-activated cytoprotective signalling at mitochondria-associated membranes (MAMs). The MAM signalling module — a protein complex at ER-mitochondria contact sites — constitutes a functional module for stress response coordination. The module is defined by spatial co-localisation and shared functional requirement for stress-induced signal transduction at membrane contact sites."

DEFS[273] = "Modules are not explicitly defined; the paper tracks longitudinal changes in cortical functional organisation in multiple sclerosis. Functional brain modules — communities of brain regions with correlated resting-state activity — are the units of analysis for characterising disease-driven cortical reorganisation. Changes in within-module and between-module functional connectivity serve as imaging biomarkers of MS-related compensatory plasticity."

DEFS[274] = "Modules are not explicitly defined; the paper studies how an EBV-encoded miRNA induces EMT and promotes cancer metastasis. The EMT regulatory module — comprising miRNA targets, EMT transcription factors, and downstream invasion-promoting genes — is co-ordinately activated by viral miRNA expression. The paper characterises the molecular pathway by which viral reprogramming of this regulatory module drives cancer cell invasion."

DEFS[275] = "Modules are transcriptional regulatory modules — groups of transcription factors and co-regulated target genes controlling vascular cambium development. The paper constructs a regulatory framework identifying co-expressed gene modules whose expression is controlled by specific transcription factor combinations. Each module corresponds to a regulatory programme active at a distinct stage of cambial cell differentiation and wood formation."

DEFS[276] = "Modules are densely connected subgraphs in biological interaction networks identified by higher-order structural patterns. HiSCF leverages network motifs and higher-order connections to identify biologically meaningful modules beyond what pairwise clustering detects. In protein interaction networks, these higher-order modules correspond to protein complexes and functional sub-networks sharing topological patterns indicative of co-complex membership."

DEFS[277] = "Modules are morphological modules — semi-independent groups of skeletal or morphological traits that co-vary within a module more than between modules. The paper evaluates statistical methods for detecting and comparing modular signal strength in morphological datasets, assessing which methods most accurately recover known module structure. Modules are defined by within-module phenotypic integration exceeding between-module integration."

DEFS[278] = "Modules are not explicitly defined; the paper characterises tricalbins as lipid transfer proteins at ER-PM contact sites. The tethering and transfer complex at ER-PM junctions — comprising tricalbins, other contact site proteins, and lipid transfer domains — constitutes a functional module for phospholipid homeostasis. The module is defined by spatial co-localisation at contact sites and collective contribution to membrane lipid composition."

DEFS[279] = "Modules are gene co-expression modules whose evolutionary conservation is assessed by phylogenomic network analysis. The paper examines which co-expression modules are conserved across deep evolutionary time versus lineage-specific, using cross-species comparison of network topology. Conserved modules reflect ancient, functionally constrained co-regulatory programmes, while lineage-specific modules represent evolutionary innovations in gene regulation."

DEFS[280] = "Modules are not explicitly defined; the paper reviews network neuroscience perspectives on learning, examining how brain network architecture supports new knowledge acquisition. Functional brain modules — communities of brain regions with correlated activity — are the units whose flexibility and integration predict learning success. The paper discusses how modular brain network properties change during and after learning episodes."

DEFS[281] = "Modules are structural sub-complexes of the condensin complex; the SMC heterodimer, kleisin, and HEAT repeat subunits constitute distinct structural and functional modules whose relative arrangement changes during the condensin ATPase cycle. Cryo-EM structures reveal a subunit flip-flop mechanism in which module positions switch between engaged and disengaged states to drive DNA looping. The module is defined by stable co-complex membership and mechanistic contribution to the condensin ATPase cycle."

DEFS[282] = "Modules are microbial community assemblages in plastisphere biofilms — co-occurring groups of microbial taxa forming distinct communities on plastic debris in freshwater wetlands. The paper characterises biofilm formation, community structure, and metabolic potential within these modules. Module membership is determined by co-occurrence network analysis of amplicon sequencing data from plastic-colonising microbiomes."

DEFS[283] = "Modules are metabolic pathway modules in genome-scale metabolic models of animals. The paper describes reconstruction methods for animal metabolic networks and their use in predicting metabolic phenotypes. Each metabolic pathway constitutes a functional module — a group of enzymatic reactions performing a defined biosynthetic or catabolic function — whose activity can be independently assessed in the model."

DEFS[284] = "Modules are not explicitly defined; the paper examines mechanisms of mutational robustness in transcriptional regulation. Regulatory modules — groups of transcription factor binding sites or co-regulatory complexes controlling shared target genes — buffer against mutations through within-module functional redundancy. The paper characterises how module architecture (binding site multiplicity, co-regulator diversity) determines phenotypic robustness to regulatory mutations."

DEFS[285] = "Modules are separable sub-networks or functional components of artificial neural networks — including convolutional filters, attention heads, or expert networks — that can be independently trained, transferred, or reused across tasks. The paper reviews modularisation techniques (mixture-of-experts, capsule networks, modular meta-learning) and their computational advantages. In biological network contexts, analogous modular components correspond to functional sub-systems with distinct input-output properties."

DEFS[286] = "Modules are not explicitly defined; the paper characterises how ZMYND8 co-localises with the NuRD complex at specific target genes and regulates transcription. The NuRD-ZMYND8 co-regulatory module is defined by stable co-complex membership and shared occupancy at specific genomic loci. The module is characterised functionally by its role in Poly(ADP-Ribose) polymerase-dependent transcriptional regulation at DNA damage sites."

DEFS[287] = "Modules are not explicitly defined; the paper reviews how ethnopharmacological knowledge informs modern natural drug discovery strategies. Bioactive natural products from traditional medicine interact with molecular pathway modules — signalling cascades, metabolic pathways, protein assemblies — to produce therapeutic effects. Network pharmacology maps these compound-pathway module interactions to identify multi-target mechanisms of action."

DEFS[288] = "Modules are not explicitly defined; the paper describes multiplex genome engineering by MAGE in yeast. Groups of co-edited genomic loci targeting a shared metabolic pathway or regulatory module constitute the units of multiplexed engineering. The paper demonstrates that simultaneous editing of multiple components within a functional module achieves more complete pathway engineering than single-target approaches."

DEFS[289] = "Modules are protein complexes detected by structural proteomics using cross-linking mass spectrometry in a thermophilic organism. Each detected protein community — a group of proteins sharing interaction interfaces and stable co-assembly — constitutes a functional module performing a defined cellular role. The paper provides a systems-level view of modular protein organisation in thermophilic cell architecture."

DEFS[290] = "Modules are not explicitly defined; the paper examines multifunctional soft machines based on stimuli-responsive hydrogels for biomedical applications. In engineered biologically-inspired soft machines, modular design involves assembling stimuli-responsive gel components with distinct mechanical and chemical response properties. Each gel component constitutes a functional module whose independent stimuli-response behaviour enables complex multi-modal device operation."

DEFS[291] = "Modules are not explicitly defined; the paper identifies moonlighting proteins — those participating in multiple distinct functional modules simultaneously — in the human protein interaction network. These multi-module proteins occupy network positions at the intersection of different communities. The paper uses network topology (between-module bridging centrality) to characterise how moonlighting protein module membership relates to essentiality and disease association."
