# Definitions part 3: rows 446-591
DEFS = {}

DEFS[446] = "Modules are network motifs — small, over-represented subgraph patterns that recur significantly more often in real networks than in randomised counterparts. The paper reviews the evolutionary origins of network motifs and proposes that they arise from selection for specific computational functions. In biological regulatory networks, motifs constitute functional modules whose topological pattern encodes a specific information-processing operation (e.g., feedforward filtering, feedback oscillation)."

DEFS[447] = "Modules are functional groups of human genes identified from genome-wide CRISPR knockout fitness profiles across many cell lines. Genes with highly correlated fitness profiles cluster into modules corresponding to shared complexes, pathways, or cellular processes. The resulting functional gene interaction network partitions the human genome into hierarchical modules enabling systematic prediction of gene function and disease relevance."

DEFS[448] = "Modules are not explicitly defined; the paper reviews differential gene regulatory network analysis to identify network changes between conditions (development, disease). Gene regulatory modules — groups of co-regulated genes controlled by shared transcription factors — constitute the functional units whose regulatory connections change between conditions. The paper characterises methods for detecting differential module wiring as a proxy for gene regulatory reprogramming."

DEFS[449] = "Modules are not explicitly defined; the paper examines a double negative feedback loop between mTORC1 and AMPK that guarantees robust autophagy induction. The mTORC1-AMPK-ULK1 regulatory module constitutes a three-component circuit performing bistable switching between anabolic and catabolic metabolic states. The module is defined by the set of protein kinases and their mutual inhibitory interactions that collectively implement switch-like autophagy regulation."

DEFS[450] = "Modules are not explicitly defined; the paper examines the network morphospace — the space of possible network structures described by structural parameters. Modular networks occupy a specific region of the morphospace characterised by high within-module connectivity and low between-module connectivity. The paper characterises how real-world biological networks are distributed in the morphospace and what evolutionary or functional constraints confine them to their specific structural niche."

DEFS[451] = "Modules are not explicitly defined; the paper examines receptor-level mechanisms required for EGF-driven ERK activity pulses. The EGFR-Ras-ERK signalling module and its associated negative feedback regulators constitute an integrated circuit generating stochastic ERK activity pulses. The paper characterises how receptor-level properties (dimerisation, internalisation) determine the statistical properties of these pulsatile signalling module outputs."

DEFS[452] = "Modules are co-expressed protein modules identified by weighted network analysis of proteogenomic data from triple-negative breast cancer. Each module corresponds to a group of proteins with correlated abundances across tumour samples, reflecting shared regulation or pathway membership. Modules associated with chemotherapy response or resistance provide mechanistic insight into the molecular determinants of treatment outcome in TNBC."

DEFS[453] = "Modules are not explicitly defined; the paper examines how ERK activity dynamics are decoded into gene expression changes. The EGFR-RAS-ERK signalling module and its transcriptional targets constitute an integrated signal processing cascade. The paper characterises how the ERK module performs linear integration of signal amplitude over time rather than detecting specific signal features, implying that ERK target gene induction reflects cumulative module activity."

DEFS[454] = "Modules are microbial functional modules — groups of co-occurring soil microbial taxa with correlated gene expression patterns that collectively perform specific ecological functions such as nitrogen cycling, carbon decomposition, or plant growth promotion. The paper predicts forest soil microbial functional modules from genetic correlation networks, identifying module compositions that determine soil ecological function. Modules are defined by co-occurrence and shared functional gene content."

DEFS[455] = "Modules are not explicitly defined; the paper describes stochastic simulation methods for biomolecular networks in dynamic environments. Biochemical reaction circuits — including signalling modules, gene regulatory circuits, and metabolic pathways — constitute the functional modules being simulated. The paper provides efficient stochastic simulation algorithms that correctly handle the dynamics of spatially distributed and temporally heterogeneous module interactions."

DEFS[456] = "Modules are not explicitly defined; the paper reviews cavity spintronics — the coupling of microwave photons with spin excitations in magnetic materials. In the context of quantum information systems, individual resonator-spin coupling elements constitute functional modules. The paper characterises how these physical modules are coupled and how their interactions produce coherent quantum phenomena relevant to quantum information processing."

DEFS[457] = "Modules are not explicitly defined; topologically associating domains (TADs) and CTCF-anchored chromatin loops constitute genomic regulatory modules — structurally defined chromosome units that organise enhancer-promoter interactions. The paper characterises how CTCF and R-loops together define the boundaries of cohesin-mediated DNA looping modules. The module is defined by its CTCF anchor positions and the cohesin-extruded loop domain that it circumscribes."

DEFS[458] = "Modules are defined in multiple ways in the paper, which explicitly surveys the concept of modularity across disciplines. The paper reviews structural definitions (densely connected subgraphs), functional definitions (coordinated activity toward a shared function), developmental definitions (semi-autonomous trait groups), and evolutionary definitions (units of heritable variation). The paper argues that different definitions capture different aspects of modularity and that no single definition is universally appropriate."

DEFS[459] = "Modules are not the primary framing; the paper argues that living things cannot be adequately understood using 20th-century machine metaphors. In the biological context, functional modules are not rigidly pre-specified components with fixed input-output relationships, but rather dynamic, context-dependent, and multi-functional assemblies. The paper proposes updated conceptual frameworks for biological organisation that acknowledge the non-modular, interactive nature of biological components."

DEFS[460] = "Modules are communities — groups of nodes in a network with more connections to each other than to the rest of the network. The paper introduces the 'modularity vitality' metric, quantifying each node's contribution to overall network community (module) structure. Nodes with high modularity vitality are central to community structure and their removal would most disrupt the modular organisation of the network. The metric is applied to biological networks to identify structurally important nodes."

DEFS[461] = "Modules are genetic circuit components — functional units (gene expression cassettes, regulatory elements, signal transduction proteins) that are rationally assembled to engineer synthetic microbial systems. The paper examines how modular design principles enable construction of increasingly complex synthetic systems from single-cell circuits to microbial consortia. Modularity is assessed by the extent to which individual circuit component behaviour is preserved upon assembly and integration with host cell context."

DEFS[462] = "Modules are genetic circuit components in synthetic biology — gene expression cassettes and regulatory elements whose collective expression imposes a metabolic burden (genetic load) on the host cell. The paper examines how resource competition for shared cellular machinery (RNAP, ribosomes) creates unintended coupling between nominally independent genetic modules. Modularity fails when modules compete for the same limiting cellular resources, causing context-dependent behaviour."

DEFS[463] = "Modules are gene co-expression modules — groups of co-regulated genes identified by differential co-expression network analysis between disease and healthy states. The paper compares methods for detecting modules whose co-expression patterns change between conditions, identifying groups of genes that become co-regulated specifically in disease states. Each disease-specific co-expression module corresponds to a regulatory programme activated or inactivated in the disease context."

DEFS[464] = "Modules are not explicitly defined; the paper presents methods for autonomous inference of complex network dynamics from incomplete data. Modular network sub-systems — groups of densely interconnected nodes that behave semi-independently — constitute the structural units that enable partial system inference. The paper characterises how network module structure can be leveraged to infer missing dynamical information from partial observations."

DEFS[465] = "Modules are transcriptomically defined cell types — groups of neurons with shared gene expression profiles constituting distinct cell-type modules within the primary motor cortex. The paper constructs a comparative taxonomy of motor cortex cell types across human, marmoset, and mouse, identifying conserved versus species-divergent cell-type modules. Conserved cell types represent evolutionarily constrained modular units of motor cortex circuit organisation."

DEFS[466] = "Modules are neuronal circuit modules — defined groups of GABAergic inhibitory neurons (chandelier cells, basket cells, Martinotti cells, VIP interneurons) that perform distinct inhibitory functions in cortical circuits. The paper reviews how inhibitory interneuron subtypes are recruited (hired) and inactivated (fired) during different brain states. Each interneuron type constitutes a distinct functional module of cortical inhibitory circuitry characterised by molecular identity, connectivity, and functional role."

DEFS[467] = "Modules are not explicitly defined; the paper uses spatial transcriptomics to characterise evolutionary and microenvironmental dynamics in colorectal cancer. Transcriptionally defined tumour cell sub-populations and spatially co-localised cell communities constitute functional modules of the tumour microenvironment. The paper characterises how these cellular modules evolve during tumour progression and how microenvironmental context shapes tumour cell module composition and identity."

DEFS[468] = "Modules are not explicitly defined; the paper reviews cellular quiescence in budding yeast, examining the molecular circuits controlling reversible exit from the cell cycle. The quiescence regulatory module — comprising CDK inhibitors, Rb-E2F-like regulators, nutrient sensing pathways (TOR, AMPK), and stress response transcription factors — constitutes the functional circuit controlling quiescence entry and exit depth. The paper characterises how this regulatory module implements graded quiescence states."

DEFS[469] = "Modules are microbial co-occurrence modules — groups of co-occurring microbial taxa that form distinct sub-networks in microbiome networks constructed from high-throughput multi-omics data. The paper reviews computational methods for constructing and analysing microbiome networks, with community detection algorithms identifying modules of ecologically associated microbial taxa. Each module corresponds to a putative guild of taxa sharing ecological niche, metabolic complementarity, or interaction partnerships."

DEFS[470] = "Modules are microbial co-occurrence modules — groups of ecologically meaningful microbial taxa identified by consensus across multiple network inference tools. The paper combines multiple network construction methods to identify robust co-occurrence modules whose ecological interpretation is supported by multiple lines of evidence. Each module corresponds to a group of taxa with shared habitat preference, metabolic exchange relationships, or ecological interaction patterns."

DEFS[471] = "Modules are not explicitly defined; the paper reviews therapeutic roles of flavonoids in cancer prevention. Signalling pathway modules involved in cancer cell survival (PI3K-AKT, MAPK, NF-κB) and apoptosis constitute the functional targets of flavonoid compounds. Network pharmacology approaches map flavonoid-module interactions, characterising how different flavonoid subclasses modulate specific signalling modules to produce anti-cancer effects."

DEFS[472] = "Modules are not explicitly defined; the paper reviews network-based technologies for early drug discovery. Disease modules — localised subnetworks of the human interactome where disease proteins cluster — are the fundamental units of network medicine drug discovery. The paper characterises how topological analysis of disease modules enables identification of drug targets, prediction of drug repurposing opportunities, and prioritisation of combination therapy strategies."

DEFS[473] = "Modules are not explicitly defined; the paper compares local and global network alignment strategies for identifying similarities between biological networks across species. Conserved subgraphs identified by both approaches correspond to evolutionarily conserved functional modules. The paper argues that local (partial match) and global (complete match) alignment approaches recover complementary aspects of modular conservation and proposes methods to reconcile them."

DEFS[474] = "Modules are not explicitly defined; the paper examines key biological processes driving pancreatic cancer metastasis using proteogenomics. Protein co-expression modules — groups of proteins with correlated abundances reflecting shared regulation or complex membership — are the units of analysis. Modules associated with metastatic capacity are identified by network analysis of proteogenomic data from primary and metastatic pancreatic tumours."

DEFS[475] = "Modules are gene regulatory modules — groups of co-regulated genes controlled by specific transcription factors in human T cells. The paper systematically discovers and perturbs regulatory genes using CRISPR screening, mapping the regulatory modules controlling T cell differentiation and function. Each module corresponds to a set of genes whose expression is co-ordinately altered by perturbation of a shared upstream regulator."

DEFS[476] = "Modules are not explicitly defined; the paper examines Mef2 transcription factor control of early B-cell development. The early B-cell gene regulatory module — comprising Mef2 transcription factors and their target genes — constitutes a regulatory circuit controlling B lineage specification and development. The paper characterises how this Mef2-centred regulatory module controls the transition between developmental stages of B-cell maturation."

DEFS[477] = "Modules are not explicitly defined; the paper examines the aspartic protease Ddi1 in DNA-protein crosslink repair. The DNA-protein crosslink repair machinery — comprising Ddi1 protease, the proteasome, and associated DNA repair factors — constitutes a functional module for removing covalently trapped DNA-protein crosslinks. The module is defined by shared functional requirement in DPC repair and the direct protein-protein interactions that co-ordinate protease and repair activities."

DEFS[478] = "Modules are functional pathway modules — groups of genes participating in specific biological pathways that collectively influence phenotypes in genome-wide association studies. The paper identifies genetic interactions between pathway modules that bridge GWAS loci, revealing epistatic relationships between distinct biological process modules. Each pathway module is defined by shared biological function and is represented as a node in a pathway interaction network."

DEFS[479] = "Modules are topologically associating domains (TADs) — hierarchically organised genomic regulatory modules that organise chromatin into self-interacting units. OnTAD identifies nested TAD hierarchies, revealing that TADs are modular structures organised at multiple scales. Higher-level TADs contain lower-level sub-TADs as nested modules. The divergence of gene activity between nested sub-TADs is characterised as a key determinant of gene regulation within the genomic module hierarchy."

DEFS[480] = "Modules are protein complexes — stable assemblies of physically interacting proteins constituting functional cellular modules. The paper reviews technologies for discovering protein-protein interactions and their application to mapping the cellular interactome. Protein complex detection by affinity purification-mass spectrometry, two-hybrid screening, and proximity labelling enables comprehensive identification of the protein complex modules that organise cellular function."

DEFS[481] = "Modules are microbial community modules — groups of co-occurring rhizosphere fungi that constitute distinct sub-networks in plant-associated microbiome networks. The paper identifies a host genotype-specific rhizosphere fungus that promotes drought resistance, characterising its interaction with other fungal community members. Module composition and the position of this keystone fungus within the community module network are examined in relation to its drought-protective function."

DEFS[482] = "Modules are not explicitly defined; the paper reviews statistical methods for proteomics data analysis. Protein co-abundance modules — groups of proteins with correlated abundance across samples identified by network analysis — constitute functional modules that can be detected from proteomics data. The paper reviews feature selection and clustering methods for identifying these modules and their association with phenotypic or clinical variables."

DEFS[483] = "Modules are not explicitly defined; the paper examines molecular mechanisms driving glioblastoma and strategies for targeted therapies. Signalling pathway modules (EGFR-RAS-MAPK, PI3K-AKT-mTOR, PDGFR) and their downstream transcriptional targets constitute functional units whose dysregulation drives glioblastoma growth. The paper characterises how combinatorial targeting of multiple signalling modules may overcome the resistance to single-pathway inhibition in glioblastoma."

DEFS[484] = "Modules are not explicitly defined; the paper examines how combined MEK and ERK inhibition overcomes therapy-mediated MAPK pathway reactivation. The MEK-ERK signalling module — comprising MEK1/2 kinases, ERK1/2 kinases, and their shared substrates and feedback regulators — constitutes an integrated signalling circuit whose reactivation after MEK inhibitor treatment is overcome by co-targeting ERK. The paper characterises the adaptive rewiring of this signalling module under therapeutic pressure."

DEFS[485] = "Modules are not explicitly defined; the centrosome and primary cilium are characterised as a hybrid organelle system with distinct but related structural modules. The centriole-centrosome module and the ciliary axoneme module are structurally distinct assemblies built from the same basal body template. The paper examines how these two organellar modules are co-ordinated and how defects in specific module components cause ciliopathies and cancer-related centrosome amplification."

DEFS[486] = "Modules are not explicitly defined; the paper examines optimal regulatory circuit topologies for fold-change detection. The fold-change detection regulatory module — comprising an incoherent feedforward loop or specific negative feedback topology — constitutes a circuit that responds to the ratio rather than absolute level of input signals. The paper identifies which circuit topologies (module architectures) enable fold-change detection and characterises their robustness properties."

DEFS[487] = "Modules are not explicitly defined; the paper examines age and sex effects on plasma metabolite association networks. Metabolite co-variation modules — groups of plasma metabolites with correlated abundances reflecting shared metabolic pathways or regulatory co-ordination — are the units of analysis. The paper characterises how module composition and within-module metabolite correlations change with age and differ between sexes."

DEFS[488] = "Modules are not explicitly defined; the paper redesigns metabolism based on orthogonality principles to reduce cross-talk between engineered and native metabolic pathways. Metabolic pathway modules — groups of enzymes performing defined biosynthetic or catabolic functions — are engineered to be orthogonal to (non-interfering with) the host metabolic network. Orthogonality principles specify how to design module interfaces that minimise unintended metabolic interactions between engineered and native modules."

DEFS[489] = "Modules are not explicitly defined; the paper examines structural brain network characteristics differentiating early multiple sclerosis from clinically isolated syndrome. Brain network modules — communities of brain regions with high within-module structural connectivity — are used as units of analysis for characterising disease-related network organisation changes. Module properties (within-module connectivity, inter-module bridging) serve as structural brain network biomarkers discriminating between early MS subtypes."

DEFS[490] = "Modules are not explicitly defined; EcoCyc is a database describing the E. coli genome, metabolic pathways, and regulatory networks. Metabolic pathways and regulatory circuits in EcoCyc constitute functional modules — groups of enzymes or regulatory proteins performing defined cellular functions. The database enables systematic querying of module membership, regulation, and metabolic connectivity in E. coli."

DEFS[491] = "Modules are not explicitly defined; the paper describes a multiplexed live-cell profiling system using Raman probes for single-cell analysis. Subcellular compartments and organelles constitute spatial modules that can be simultaneously profiled for biochemical state. The paper characterises how multiparameter Raman profiling can monitor the state of multiple spatial modules — nucleus, mitochondria, cytoplasm — simultaneously in individual living cells."

DEFS[492] = "Modules are not explicitly defined; the paper uses integrative network analysis to identify cell-specific trans-regulators of m6A. The m6A regulatory module — comprising writer, eraser, and reader proteins — constitutes the functional machinery for m6A-based epitranscriptomic regulation. The paper identifies cell-type-specific trans-regulators that modulate the activity of this regulatory module, revealing how m6A patterns are shaped by cell identity."

DEFS[493] = "Modules are not explicitly defined; the paper examines axo-axonic cells (chandelier cells) in hippocampal circuits. Chandelier cells constitute a distinct functional circuit module — a specific interneuron sub-type that inhibits the axon initial segments of pyramidal neurons. The paper characterises how this module is recruited during hippocampal activity and how its inhibitory action on the spike generation module of pyramidal cells shapes network activity."

DEFS[494] = "Modules are not explicitly defined; the paper examines metabolic control of cell growth and cell division in animal cells. The cell size homeostasis regulatory module — comprising growth rate sensors, nutrient signalling pathways (mTOR, AMPK), cell cycle regulators, and growth factor inputs — constitutes the functional circuit co-ordinating growth and division. The paper characterises how metabolic inputs into this regulatory module determine when cells reach a threshold size sufficient to trigger division."

DEFS[495] = "Modules are not explicitly defined; the paper describes in situ characterisation and manipulation of biological systems with CRISPR tools. Gene regulatory circuits and cellular signalling pathways targeted by CRISPR constitute functional modules for targeted biological manipulation. The paper reviews how modular CRISPR architectures (different guide RNAs, Cas variants, effector domains) can be deployed to manipulate specific regulatory modules in living cells."

DEFS[496] = "Modules are explicitly defined; miRNA551b-3p activates an oncostatin signalling module for cancer progression. The oncostatin module is a functional signalling circuit comprising miR551b-3p, its target genes, and the STAT3/oncostatin M signalling cascade that it activates. The module is defined by the set of interacting molecular components whose co-ordinated activity drives triple-negative breast cancer progression, with the paper characterising the module boundaries by epistatic analysis."

DEFS[497] = "Modules are genetic circuit modules — defined gene expression cassettes with characterised input-output properties. The paper examines how resource competition for shared cellular machinery (RNAP, ribosomes) causes winner-takes-all dynamics that redirect cascading cell fate transitions. Modularity fails because competing modules drawing on the same limiting resources are not independent; the paper characterises how resource competition creates unintended coupling between nominally separate genetic modules."

DEFS[498] = "Modules are not explicitly defined; the paper examines astrocyte-neuron interactions critical for Alzheimer's disease pathogenesis. Astrocyte-neuron signalling modules — defined sets of astrocyte-secreted factors, neurotrophins, and synaptic modulatory proteins — constitute functional communication units linking astrocyte state to neuronal function. The paper characterises how disruption of these intercellular communication modules contributes to synaptic dysfunction in AD."

DEFS[499] = "Modules are not explicitly defined; PaintOmics is a tool for integrative multi-omics visualisation using biological pathway maps. Metabolic and signalling pathways serve as functional modules onto which multi-omics data are mapped. The paper describes how PaintOmics enables visualisation of pathway module activity across omics data layers, facilitating identification of dysregulated modules from integrated transcriptomics, proteomics, and metabolomics datasets."

DEFS[500] = "Modules are genetic circuit modules — specifically, a proportional-integral feedback control circuit constituting a regulatory module for achieving robust homeostasis in mammalian cells. The circuit module comprises a sensor element detecting the regulated variable, an actuator element implementing proportional-integral feedback, and defined molecular interactions between them. The module is designed to function as an autonomous controller embedded in the cellular signalling context."

DEFS[501] = "A module is explicitly defined as the EGFR-HER2 signalling complex — a receptor heterodimer that functions as an integrated signalling module at the cell surface. The EGFR-HER2 module is characterised through a stem cell biology lens, examining how the module is regulated by HER2/ERBB2 overexpression and how its dysregulation drives cancer. The module definition includes the receptor pair, their shared ligands, and their coupled downstream signalling effectors that collectively determine cell fate decisions."

DEFS[502] = "Modules are not explicitly defined; the paper describes a deep learning method for protein function prediction from sequence through protein language model features. Protein interaction modules — groups of proteins with shared sequence features and functional roles — provide the training signal for the predictive model. The method implicitly treats functional groups defined by Gene Ontology terms as the modular units of protein function."

DEFS[503] = "Modules are not explicitly defined; the paper examines redundancy, feedback, and robustness in the Arabidopsis BZR/BES-BIM transcription factor network. The brassinosteroid signalling regulatory module — comprising BZR/BES transcription factors, BIM co-regulators, upstream BIN2 kinase, and target gene promoters — constitutes a functional regulatory circuit for brassinosteroid-responsive development. Redundancy within this module buffers against perturbation of individual components."

DEFS[504] = "Modules are not explicitly defined; the paper integrates gene co-expression network analysis with the human interactome to move from correlation toward causation in network analysis. Protein interaction modules — groups of proteins with shared interaction partners — provide a causal framework for interpreting co-expression modules. The paper characterises how combining interaction and expression network analysis enables identification of functionally meaningful gene regulatory modules."

DEFS[505] = "Modules are protein complexes; the MRPP1/MRPP2 complex constitutes a functional tRNA-maturation module in human mitochondria. The MRPP1-MRPP2 heterodimer forms the protein component of mitochondrial RNase P, which cleaves tRNA 5'-ends from polycistronic mitochondrial transcripts. The module is defined by stable protein co-complex formation and shared functional requirement for mitochondrial tRNA maturation and RNA processing."

DEFS[506] = "Modules are not explicitly defined; the paper examines how activity-mediated transitions in transcription occur during early postnatal neuronal maturation. Transcriptional regulatory modules — groups of transcription factors and co-regulated target genes activated by neuronal activity — constitute the functional units controlling experience-dependent neuronal maturation. The paper characterises how activity drives transitions between transcriptional module states during the critical period of postnatal brain development."

DEFS[507] = "Modules are gene co-expression modules and regulatory network modules identified from single-cell genomics data across 388 human brains. Each module corresponds to a group of genes with correlated expression across cells and tissues, reflecting shared transcriptional regulation or functional co-participation. The paper constructs cell-type-specific regulatory networks and identifies modules whose activity is associated with brain disorders, age, and individual differences in brain gene expression."

DEFS[508] = "Modules are not explicitly defined; the paper reviews the Csr/Rsm RNA-binding protein global regulatory system in Gammaproteobacteria. The Csr regulatory module — comprising the CsrA RNA-binding protein, its regulatory non-coding RNAs (CsrB, CsrC), and the regulatory kinase CsrD — constitutes a functional global regulatory circuit controlling carbon metabolism, biofilm formation, and motility. The module is defined by the protein-RNA interactions and feedback loops that implement its global regulatory logic."

DEFS[509] = "Modules are not explicitly defined; the paper bridges mechanistic and phenomenological models of complex biological systems. In mechanistic modelling, pathway-level sub-systems constitute modules whose behaviour is described by differential equations. Phenomenological abstractions of these mechanistic modules — reduced models capturing input-output behaviour — enable integration of module-level knowledge into larger system models. The paper provides methods for connecting these modelling levels."

DEFS[510] = "Modules are not explicitly defined; the paper explores prognostic biomarkers in triple-negative breast cancer using network analysis. Co-expressed protein and gene modules — groups of co-regulated molecules reflecting shared pathway membership — are the units of analysis for identifying prognostic signatures. The paper identifies modules significantly associated with patient survival in TNBC and characterises the biological processes they represent."

DEFS[511] = "Modules are microbial community modules — groups of co-occurring soil microbial taxa forming distinct sub-networks in salinized soil microbiomes. The paper examines how organic amendment remediation of soil salinization affects microbial module composition and ecological function. Modules are identified by co-occurrence network analysis and interpreted in terms of shared ecological roles in soil nutrient cycling and organic matter decomposition."

DEFS[512] = "Modules are not explicitly defined; the paper constructs individualised interactomes for network-based precision medicine in hypertension. Disease modules — localised subnetworks of the personalised interactome in which disease-associated proteins cluster — constitute the functional units of network medicine analysis. The paper characterises how individual-level variation in protein interaction network structure shapes the disease module landscape and informs personalised therapeutic targeting."

DEFS[513] = "Modules are not explicitly defined; the paper reviews methods for depicting overlap in systematic review overviews. In the context of evidence synthesis networks, modules correspond to groups of systematic reviews addressing related questions or sharing study populations. The paper introduces graphical and tabular methods for visualising the overlap structure between these evidence modules."

DEFS[514] = "Modules are not explicitly defined; the paper examines context-dependent, combinatorial logic of BMP signalling. The BMP signalling module — comprising BMP ligands, receptor combinations, SMAD transcription factors, and co-regulatory proteins — exhibits combinatorial signal processing in which different receptor and ligand combinations produce distinct transcriptional outputs. The paper characterises how context-specific module configurations implement distinct cell fate decisions."

DEFS[515] = "Modules are communities identified from multiplex biological networks — groups of nodes that are consistently co-clustered across multiple network layers (e.g., protein interaction, co-expression, genetic interaction). The paper presents methods for identifying modules from multiplex networks, treating a module as a group of nodes sharing membership across multiple types of biological association. This multiplex community definition captures more comprehensive functional relationships than any single network layer alone."

DEFS[516] = "Modules are functional brain modules — communities of structurally and functionally connected brain regions identified from white and grey matter connectivity data. The paper examines how increased structural network connectivity within and between brain modules compensates for functional decline in early multiple sclerosis. Module-level connectivity changes are characterised as adaptive plasticity responses to early white matter lesion damage."

DEFS[517] = "Modules are structural sub-complexes of condensin; the SMC heterodimer head domains, the kleisin subunit, and the HEAT-repeat (HAWK) subunits constitute distinct structural modules within condensin. The paper characterises the structural basis of an asymmetric condensin ATPase cycle, showing that the two HAWK subunits engage the SMC ATPase heads asymmetrically. This asymmetric module arrangement is mechanistically linked to the directionality of DNA loop extrusion."

DEFS[518] = "Modules are microbial community modules — groups of co-occurring bacteria forming distinct sub-networks in the maize root microbiome across different root niches (rhizosphere, rhizoplane, endosphere). The paper examines how maize root niche determines bacterial response variation to organic pollution, with different microbial modules in different niches showing distinct sensitivities. Module composition and response patterns are characterised by co-occurrence network analysis."

DEFS[519] = "Modules are not explicitly defined; the paper reviews biological feedback control at multiple scales. Feedback loop circuits within gene regulatory networks, signalling pathways, and physiological systems constitute functional modules whose dynamics determine system behaviour. The paper emphasises that feedback loops — from molecular to organismal scale — are the fundamental modular units of biological control and that understanding their operation is essential for understanding biological function."

DEFS[520] = "Modules are not explicitly defined; the paper examines challenges and opportunities for digital twins in precision medicine for cancer. Cancer pathway modules — signalling cascades, metabolic pathways, and gene regulatory networks disrupted in tumours — constitute the functional sub-systems being represented in digital twin models. The paper characterises how multi-omics data integration enables construction of patient-specific module activity profiles for personalised medicine."

DEFS[521] = "Modules are not explicitly defined; the paper examines a parallel adder mechanism co-ordinating cell cycle progression and size in mycobacteria. The cell size control regulatory module — comprising an adder-type division mechanism, nutrient sensing, and cell cycle checkpoints — constitutes the functional circuit determining when cells have grown sufficiently to divide. The paper characterises how this regulatory module implements parallel rather than serial size and cell cycle co-ordination."

DEFS[522] = "Modules are not explicitly defined; the paper identifies cell-type-specific eQTLs in primary melanocytes as a resource for identifying GWAS variants. Gene co-expression modules in melanocytes — groups of co-regulated genes sharing genetic regulatory variants — constitute functional units whose expression is jointly controlled by specific genetic loci. The paper characterises how cell-type-specific module regulation reveals melanocyte-specific mechanisms underlying pigmentation and skin disease genetics."

DEFS[523] = "Modules are microbial community modules — groups of co-occurring soil microbial taxa with correlated abundances across soil pH gradients. The paper examines how soil pH as a key edaphic factor shapes the distribution and co-occurrence patterns of microbial taxa, identifying modules of pH-sensitive co-occurring microbes. Modules are detected by network community detection and interpreted as groups of taxa occupying similar pH niches or exhibiting pH-dependent ecological interactions."

DEFS[524] = "Modules are not explicitly defined; the paper provides a dense functional and molecular readout of a circuit hub in sensory cortex. The characterised circuit hub — a specific cortical layer or cell type — constitutes a functional circuit module receiving and integrating diverse inputs. The paper maps the input connectivity, gene expression, and functional properties of this module to reveal its computational role in sensory information processing."

DEFS[525] = "Modules are neuronal circuit modules — defined groups of neurotensinergic neurons in the thalamus and amygdala that together constitute a functional sleep regulatory circuit. The paper characterises how this thalamo-amygdala module regulates sleep and arousal, identifying the cellular and molecular components of the module and their functional connections. The sleep regulatory module is defined by the characteristic connectivity pattern and neurotensin receptor expression of its component neurons."

DEFS[526] = "Modules are not explicitly defined; the paper constructs a comprehensive, clinically informed map of genetic dependencies in cancer cell lines. Gene co-dependency modules — groups of genes whose essentiality profiles are correlated across cancer lines, reflecting shared pathway membership — constitute the functional units of analysis. The paper characterises the clinical relevance of these cancer dependency modules and their association with genomic features."

DEFS[527] = "Modules are not explicitly defined; the paper maps the proteomic landscape of genome-wide genetic perturbations in yeast. Co-regulated protein sets whose abundances change in response to related genetic perturbations constitute functional modules of the cellular proteome. The paper characterises how perturbation of specific genes propagates through the protein interaction network, revealing the modular organisation of yeast cell biology at the proteomic level."

DEFS[528] = "Modules are not explicitly defined; the paper examines combinatorial assembly and design of enzymes for synthetic biology. Enzyme domain modules — discrete structural and functional domains within multi-domain enzyme architectures — constitute the units of combinatorial assembly. The paper characterises principles for designing novel enzyme functions by recombining domain modules, drawing on the natural modularity of enzyme architecture as a design framework."

DEFS[529] = "Modules are not explicitly defined; the paper examines how vasoactive intestinal peptide-expressing (VIP) interneurons are impaired in a mouse model of Alzheimer's disease. VIP interneurons constitute a distinct functional circuit module of cortical inhibitory circuitry. The paper characterises how this interneuron module is specifically vulnerable to amyloid-related pathology and how its dysfunction disrupts cortical gamma oscillation and cognitive function."

DEFS[530] = "Modules are not explicitly defined; the paper reviews computational oncology methods for multi-omics data analysis. Molecular pathway modules — signalling cascades, metabolic pathways, gene regulatory circuits — are the functional units of analysis in systems oncology. The paper characterises how integrative multi-omics approaches identify dysregulated pathway modules in cancer and translate these findings into predictive biomarkers and therapeutic targets."

DEFS[531] = "Modules are not explicitly defined; the paper reviews the Rcs system in Enterobacteriaceae and its roles in envelope stress response. The Rcs phosphorelay module — comprising the outer membrane sensor protein RcsF, the phosphorelay components RcsC and RcsD, and the response regulator RcsB — constitutes a functional signal transduction module linking envelope stress to transcriptional output. The module is defined by the phosphorelay cascade and the set of target genes collectively regulated by RcsB."

DEFS[532] = "Modules are protein sub-complexes; the paper characterises the structural basis for Scc3-dependent cohesin recruitment to chromatin. Scc3/SA constitutes a key cohesin regulatory module that bridges the SMC-kleisin ring to chromatin-binding accessory factors. The paper reveals how Scc3 is structurally positioned within the cohesin module architecture to co-ordinate loader recruitment and chromatin association."

DEFS[533] = "Modules are not explicitly defined; the paper examines coactivator-dependent oscillation of chromatin accessibility that dictates circadian gene expression. The circadian clock gene regulatory module — comprising core clock proteins (BMAL1, CLOCK, CRY, PER), their coactivators, and chromatin remodelling factors — constitutes a functional oscillatory circuit. The paper characterises how chromatin accessibility cycling within this transcriptional module drives rhythmic gene expression."

DEFS[534] = "Modules are morphological modules — semi-independent groups of vertebral traits that exhibit coordinated evolution. The paper examines adaptation and constraint in the evolution of the mammalian backbone by characterising which vertebral regions co-vary as modules and which are evolutionary independent. Modules are defined by within-module morphological integration exceeding between-module integration, and the paper characterises how functional demands (locomotion, respiration) constrain module evolution."

DEFS[535] = "Modules are not explicitly defined; the paper reviews pathway-based tools for visualising genetic variants. Biological pathways serve as predefined functional modules onto which genetic variants are mapped for pathway enrichment analysis. The paper characterises how different visualisation approaches help interpret the distribution of genetic variants across pathway modules and identify modules enriched for disease-associated variation."

DEFS[536] = "Modules are not explicitly defined; the paper presents inductive inference of gene regulatory networks using supervised and semi-supervised learning. Gene regulatory modules — groups of co-regulated genes controlled by shared transcription factors — constitute the functional units whose regulatory relationships are inferred. The paper characterises how training data from known regulatory interactions can be used to induce network module structure from gene expression data."

DEFS[537] = "Modules are not explicitly defined; the paper examines MAPK and PI3K signalling at the crossroads of neural crest development and cancer. The MAPK (RAS-RAF-MEK-ERK) and PI3K-AKT signalling modules constitute distinct but interconnected signalling pathways that are co-ordinately regulated during neural crest development. The paper characterises how the interaction between these two signalling modules determines cell fate decisions in neural crest cells and their dysregulation in neural crest-derived cancers."

DEFS[538] = "Modules are not explicitly defined; the paper reviews signalling to and from RNA Polymerase III transcription machinery. The RNA Pol III transcription module — comprising Pol III subunits, TFIIIB and TFIIIC initiation factors, and associated regulators — constitutes a functional assembly for transcribing small structural RNAs. The paper characterises how cellular signalling pathways (mTOR, RAS, Rb) regulate the activity of this transcription module."

DEFS[539] = "Modules are functional pathway modules — groups of genes participating in specific signalling or metabolic pathways that collectively influence cancer phenotypes. The paper uses pathway-based discovery of genetic interactions in breast cancer, identifying pairs of pathway modules whose simultaneous perturbation produces epistatic effects. Each pathway module is defined by shared biological function and the genetic interactions between modules reveal pathway-level epistatic architecture in breast cancer."

DEFS[540] = "Modules are not explicitly defined; the paper examines how the Integrator complex regulates RNA Polymerase II transcription and RNA processing. The Integrator complex itself constitutes a modular enzymatic machine whose phosphatase (INTS6, PP2A) and endonuclease (INTS4, INTS9, INTS11) sub-complexes constitute distinct functional modules with separable activities in promoter-proximal pausing regulation and snRNA 3'-end processing."

DEFS[541] = "Modules are not explicitly defined; the paper combines graph neural networks with capsule networks for link prediction. In biological network applications, protein complex modules and functional sub-networks constitute the structural units whose interaction predictions are the target. The paper demonstrates that combining local node representation learning with capsule-based routing improves prediction of edges within and between biological network modules."

DEFS[542] = "Modules are not explicitly defined; the paper introduces the 'effective graph' — a reduced representation of a network that captures canalization and redundancy. Network modules are implicitly defined by the effective graph structure: groups of nodes with robust information flow pathways that remain functional under perturbation. The effective graph reveals which network sub-structures constitute robust modular units and which edges are redundant."

DEFS[543] = "Modules are not explicitly defined; the paper examines BRAF and MEK inhibition for melanoma treatment. The BRAF-MEK-ERK signalling module and its associated feedback regulators constitute the therapeutic target network. The paper characterises how co-targeting the MEK and ERK nodes of this signalling module overcomes adaptive resistance, treating the cascade as a functional circuit whose downstream nodes must be co-inhibited to prevent reactivation."

DEFS[544] = "Modules are not explicitly defined; the paper constructs an integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types. Transcriptomically defined cell types constitute functional circuit modules of the motor cortex, each characterised by a shared gene expression programme and epigenomic state. The paper characterises how module-defining transcriptional and epigenomic programmes correspond to known motor cortex cell classes and their functional roles."

DEFS[545] = "Modules are disease modules — groups of genes and proteins whose interaction network neighbourhood is enriched for disease-associated genetic variants or expression changes. The paper reviews network-based approaches for decoding disease from genomes, using network module analysis to translate genetic associations into biological mechanisms. Disease modules are identified as topological sub-networks in protein interaction networks where disease signals cluster."

DEFS[546] = "Modules are not explicitly defined; the paper reviews molecular mechanisms regulating animal cell size homeostasis. The cell size regulatory module — comprising growth rate sensors, cell cycle checkpoints (Wee1, CDK1), and nutrient signalling pathways (mTOR, AMPK) — constitutes the functional circuit co-ordinating growth with division. The paper characterises how these regulatory module components are integrated to achieve cell size homeostasis at the population level."

DEFS[547] = "Modules are not explicitly defined; the paper examines network topologies that achieve dual function of adaptation and noise attenuation. Regulatory circuit modules — specific network topologies including incoherent feedforward loops and negative feedback architectures — constitute the functional units capable of implementing both adaptation and noise filtering simultaneously. The paper identifies which module topologies can achieve this dual function and characterises their parameter sensitivity."

DEFS[548] = "Modules are not explicitly defined; the paper reviews feedback regulation in cell signalling and its lessons for cancer therapeutics. Negative and positive feedback loop modules within signalling networks constitute the functional units that determine network dynamics and drug response. The paper characterises how feedback module architecture (gain, time constant, sign) determines whether signalling circuits will adapt to or be permanently altered by therapeutic perturbation."

DEFS[549] = "Modules are not explicitly defined; the paper uses network-based combinatorial CRISPR-Cas9 screens to identify synergistic interactions between cancer vulnerabilities. Functional pathway modules — groups of genes participating in the same cellular process — are the units of analysis for identifying within-module and between-module synergistic genetic interactions. The paper characterises which combinations of module perturbations produce stronger-than-expected cancer cell killing."

DEFS[550] = "Modules are not explicitly defined; the paper examines network-level macroscale structural connectivity and its role in predicting disease propagation in multiple sclerosis. Structural brain network modules — communities of brain regions with high white matter connectivity — serve as units of analysis for characterising how disease spreads through the network. Module structure determines which brain regions are most vulnerable to damage propagation from early lesion sites."

DEFS[551] = "A module is explicitly defined as a multi-functional genetic circuit — a gene regulatory network component that performs two or more distinct biological functions. The paper characterises a spectrum of modularity in multi-functional gene circuits, distinguishing fully modular (independent function modules), semi-modular (partially overlapping), and non-modular (fully integrated) circuit architectures. Modularity is assessed by the degree to which functional outputs can be independently tuned by genetic perturbation of circuit components."

DEFS[552] = "Modules are functional communities of brain regions — groups of brain areas with correlated resting-state or task-related functional connectivity forming modules in brain network analyses. The paper examines how long-term athletic training modifies the modular structure and organisation of the brain network. Module composition, within-module connectivity, and between-module integration are the network metrics used to characterise training-induced brain plasticity."

DEFS[553] = "Modules are not explicitly defined; SGD is a database for the Saccharomyces cerevisiae genome, including gene function annotations, protein interactions, and genetic interactions. Protein complexes and metabolic pathways in SGD constitute functional modules whose members are annotated with shared GO terms and interaction data. The paper describes new data and collaboration features expanding the modular functional annotation of the yeast genome."

DEFS[554] = "Modules are not explicitly defined; the paper integrates multiple genomic and functional datasets to provide new insights on human essential genes. Gene co-essentiality modules — groups of genes whose essentiality profiles are correlated across cell lines, reflecting shared pathway membership — constitute functional units of cellular viability. The paper characterises essential gene modules and their enrichment in specific biological processes and protein complexes."

DEFS[555] = "Modules are not explicitly defined; the paper examines environment-to-phenotype mapping and adaptation strategies under varying environmental conditions. In gene regulatory network terms, adaptation modules — regulatory circuit motifs (incoherent feedforward loops, negative feedback) enabling perfect or partial adaptation — constitute the functional units of environmental response. The paper characterises which module architectures enable appropriate phenotypic responses across diverse environmental regimes."

DEFS[556] = "Modules are not explicitly defined; the paper reviews human information processing in complex networks from a network science perspective. Brain network modules — communities of functionally specialised brain regions — constitute the processing units of the cognitive system. The paper examines how modular brain network organisation balances specialised local processing within modules with integrated global communication between modules to support complex cognition."

DEFS[557] = "Modules are not explicitly defined; the paper examines how tau reduction affects excitatory and inhibitory neurons differently in Alzheimer's disease. Excitatory and inhibitory neuronal sub-networks constitute distinct functional circuit modules of hippocampal networks. The paper characterises how tau reduction differentially affects the synaptic and excitability properties of these distinct circuit modules, revealing module-specific vulnerability in AD."

DEFS[558] = "Modules are not explicitly defined; the paper examines immunosuppressive traits of hybrid epithelial/mesenchymal (E/M) phenotypes in cancer. The E/M regulatory module — comprising EMT transcription factors and their targets — operates in intermediate states that confer immunosuppressive properties. The paper characterises how partial activation of the EMT regulatory module produces hybrid E/M states with distinct immune evasion properties compared to fully epithelial or mesenchymal states."

DEFS[559] = "Modules are not explicitly defined; the paper examines pattern recognition of daily activity patterns using human mobility models. In the context of activity networks, modules correspond to clusters of individuals with similar daily activity patterns or co-location signatures. The paper characterises how network-based pattern recognition methods identify these behavioural modules and what they reveal about social structure and activity organisation."

DEFS[560] = "Modules are not explicitly defined; the paper presents a transformer-based method for identifying influential nodes in complex networks. Network communities (modules) — groups of densely interconnected nodes — serve as the structural context for identifying influential nodes. Nodes that are highly connected within their module and serve as bridges between modules are predicted to be most influential in spreading information or perturbations through the network."

DEFS[561] = "Modules are disease modules — localised subnetworks of the human interactome in which disease-associated proteins cluster together. Network medicine in pathobiology uses disease module analysis to identify the molecular mechanisms of disease, predict drug targets, and understand disease comorbidities. A disease module is defined topologically by the proximity of its member proteins in the interaction network and functionally by the biological processes they collectively represent."

DEFS[562] = "Modules are not explicitly defined; the paper uses structure-based modelling to dissect RAF inhibitor resistance mechanisms. The RAF signalling module — comprising BRAF, CRAF, their dimerisation interface, and downstream MEK-ERK effectors — constitutes an integrated signalling unit. The paper characterises how structural changes in RAF dimerisation produce paradoxical activation, revealing how the architecture of the signalling module determines drug sensitivity and resistance."

DEFS[563] = "Modules are not explicitly defined; the paper examines the misuse of the Michaelis-Menten rate law in protein interaction network models. Protein signalling modules whose kinetics are described by mass-action rather than Michaelis-Menten equations can have qualitatively different dynamic behaviour. The paper warns that applying inappropriate kinetic rate laws to molecular module interactions can produce incorrect predictions of module-level dynamics and network behaviour."

DEFS[564] = "Modules are not explicitly defined; the paper reviews redox systems biology using the cysteine redoxome. Cysteine-containing proteins that are coordinately regulated by cellular redox state constitute functional redox modules — groups of proteins whose thiol modification state changes together in response to oxidative stress. Network analysis of the cysteine redoxome reveals redox module organisation and identifies hub proteins serving as redox signal transducers."

DEFS[565] = "Modules are not explicitly defined; the paper examines neurofibromin as an estrogen receptor-alpha transcriptional co-repressor in breast cancer. The neurofibromin-ER-alpha co-regulatory complex constitutes a functional module linking RAS-MAPK regulation (NF1 function) to nuclear steroid receptor-mediated transcription. The paper characterises how loss of this regulatory module contributes to both RAS pathway activation and oestrogen-responsive gene deregulation in breast cancer."

DEFS[566] = "Modules are not explicitly defined; the paper examines an immediate-late gene expression module that decodes ERK signal duration. The immediate-late gene module — a group of genes whose transcriptional induction is delayed relative to immediate-early genes but requires sustained ERK activity — constitutes a functional decoding circuit. The paper characterises how this gene module's dependence on sustained versus transient ERK activity implements duration-dependent signal decoding."

DEFS[567] = "Modules are genetic circuit modules — functional gene regulatory units whose context-dependent behaviour is managed by synthetic controller circuits. The paper describes context-aware synthetic biology strategies that use feedback controllers to make genetic module performance robust to cellular context variation. A module in this framework is a gene circuit component whose input-output behaviour should be context-independent but is in practice coupled to host cell state."

DEFS[568] = "Modules are not explicitly defined; the paper examines childhood trauma and altered functional connectivity between amygdala and medial prefrontal cortex. The amygdala-mPFC circuit constitutes a functional brain module mediating emotional regulation and fear response. The paper characterises how trauma-related changes in the functional connectivity of this circuit module are associated with adult psychopathology risk."

DEFS[569] = "Modules are not explicitly defined; the paper characterises the protein organisation of the red blood cell. The red blood cell cytoskeleton — comprising spectrin, ankyrin, Band 3, protein 4.1, and associated proteins — constitutes a functional structural module whose precise subunit organisation determines cell deformability and membrane stability. The paper maps the proteome and protein organisation of the red blood cell, identifying modular assembly principles of the membrane cytoskeleton."

DEFS[570] = "Modules are not explicitly defined; the paper reviews organelle crosstalk in the kidney. Organelles (mitochondria, lysosomes, ER, peroxisomes) constitute structural and functional modules within renal cells whose physical and chemical interactions at membrane contact sites co-ordinate cellular metabolism and stress responses. The paper characterises how inter-organelle module communication is disrupted in renal disease and how restoring normal inter-module crosstalk may be therapeutic."

DEFS[571] = "Modules are functional communities of brain regions identified by modular structure analysis of structural and functional brain networks in schizophrenia. The paper examines modular-level alterations in structure-function coupling in schizophrenia, characterising how the relationship between structural connectivity modules and functional activity modules is disrupted in the disorder. Each module is defined as a group of brain regions with high within-module structural or functional connectivity."

DEFS[572] = "Modules are communities of neurons in the Drosophila connectome — groups of neurons with denser within-group than between-group connectivity. The paper characterises network statistics of the whole-brain Drosophila connectome, including modularity, small-worldness, and hub connectivity. Network modules in the connectome correspond to anatomically and functionally related neuronal groups performing shared computational roles in the fly brain."

DEFS[573] = "Modules are microbial keystone taxa and their associated co-occurrence modules — groups of ecologically associated microbes that co-occur with keystone taxa in plant microbiomes. The paper explores biocontrol agents from these microbial modules, identifying which community members associated with keystone taxa in the plant microbiome contribute to biological control of pathogens. Module membership and co-occurrence patterns are used to prioritise candidate biocontrol agents."

DEFS[574] = "Modules are not explicitly defined; the paper maximises binary interactome mapping efficiency for the human protein interactome. Protein interaction communities — dense subgraphs in the mapped interactome corresponding to protein complexes and functional modules — are the biological units being systematically mapped. The paper develops screening strategies that maximise the fraction of true interactions detected per assay, enabling more complete module discovery per experimental effort."

DEFS[575] = "Modules are functional communities of brain regions — groups of prefrontal cortical and subcortical brain areas forming modules in structural and functional connectivity networks. The paper examines aberrant maturation and connectivity of prefrontal cortex circuits in schizophrenia, characterising which functional modules are most affected by the neurodevelopmental disruption. Module-level connectivity abnormalities are associated with specific symptom dimensions in schizophrenia."

DEFS[576] = "Modules are regulatory switch modules — stable dynamical components of Boolean network models that capture bistable or multi-stable regulatory sub-networks. The paper performs a meta-analysis of Boolean network models across biological systems, identifying design principles for robust regulatory function. Modules are defined as minimal sub-networks that implement stable dynamical states (attractors), and their composition reveals recurring design principles across diverse biological regulatory contexts."

DEFS[577] = "Modules are functional communities of brain regions identified from baseline resting-state functional connectivity networks. The paper examines how baseline network module architecture predicts future learning ability, characterising which module properties (flexibility, integration, segregation) at rest best predict subsequent learning performance. Module structure is defined by community detection of functional connectivity matrices and characterised by standard graph theoretic metrics."

DEFS[578] = "Modules are functional communities of brain regions — groups of brain areas characterised by strong within-module functional or effective connectivity. The paper reviews functional and effective connectivity techniques for understanding brain circuits, treating modules as the fundamental units of neural information processing. The paper characterises how different connectivity analysis methods (structural equation modelling, DCM, Granger causality) reveal different aspects of modular brain organisation."

DEFS[579] = "Modules are genetic circuit modules — specifically, a synthetic gene oscillator circuit designed to slow ageing. The engineered oscillator module comprises a minimal set of regulatory interactions (repressor-activator loop) producing sustained oscillations in target gene expression. The paper examines how this regulatory module can be used to extend lifespan by periodically modulating expression of ageing-related genes through programmed oscillatory circuit activity."

DEFS[580] = "Modules are communities — groups of nodes in a network that are more densely interconnected with each other than with the rest of the network. The paper introduces a 'local dominance' method for identifying communities that does not require global optimisation. In biological networks, these locally dominant communities correspond to protein complexes, co-expression clusters, or regulatory modules whose dense internal connectivity is detectable through local structural analysis."

DEFS[581] = "Modules are not explicitly defined; the paper examines how Akt phosphorylates insulin receptor substrate (IRS) to limit PI3K-mediated PIP3 production. The PI3K-AKT-IRS negative feedback module — comprising PI3K, AKT, IRS, and feedback phosphorylation sites — constitutes a regulatory circuit limiting its own activation. The paper characterises how this feedback module implements adaptation in the PI3K-AKT signalling pathway and how its disruption contributes to insulin resistance."

DEFS[582] = "Modules are not explicitly defined; the paper reviews clinical epigenetics settings for cancer and cardiovascular diseases. Epigenetic regulatory modules — groups of co-regulated genes sharing chromatin modifications, DNA methylation patterns, or histone marks — constitute functional units of epigenetic regulation. The paper characterises how epigenetic module dysregulation contributes to disease and how clinical epigenetic profiling can identify module-level biomarkers and therapeutic targets."

DEFS[583] = "Modules are communities — groups of nodes in complex networks with denser internal than external connections. Graphia is a platform for graph-based visualisation and analysis enabling identification and visualisation of network communities (modules) in large biological datasets. In biological networks, these communities correspond to protein complexes, co-expression clusters, or metabolic sub-networks. The paper describes how Graphia enables interactive exploration of modular network organisation in high-dimensional biological data."

DEFS[584] = "Modules are not explicitly defined; the paper examines how an E3 ligase network engages GCN1 to promote degradation of translation-stalling nascent polypeptides. The ribosome quality control (RQC) module — comprising the ribosome, GCN1, E3 ubiquitin ligases, and the CDC48/p97 extraction machinery — constitutes a functional degradation assembly at stalled ribosomes. The module is defined by functional co-operation in recognising and clearing stalling translation products."

DEFS[585] = "Modules are not explicitly defined; the paper reviews spectral alignment methods for aligning graphs based on spectral properties of their adjacency matrices. In biological network alignment, conserved spectral sub-spaces correspond to preserved modular structures across species' networks. Spectral alignment methods identify module correspondences by matching eigenspace representations rather than direct node-node alignment."

DEFS[586] = "Modules are not explicitly defined; the paper examines how the circadian clock and environment drive cell size control in cyanobacteria. The circadian clock module — comprising the KaiA-KaiB-KaiC oscillator and its output pathways — constitutes a functional timekeeping circuit that gates cell division to specific circadian phases. The interaction between the clock module and nutrient sensing modules determines how environmental cues modulate the cell size set-point in cyanobacteria."

DEFS[587] = "Modules are not explicitly defined; the paper examines an IGF2-ID1-IGF2 autocrine circuit maintaining breast cancer stem cell identity. The autocrine regulatory module — comprising IGF2 ligand, its receptor, the helix-loop-helix inhibitor ID1, and their positive feedback interactions — constitutes a self-sustaining circuit module maintaining stem cell identity. The paper characterises how this positive feedback module is addicted to its own activity and how disrupting the module reduces stem cell frequency."

DEFS[588] = "Modules are not explicitly defined; the paper surveys pathway maps in cancer systems biology. Signalling and metabolic pathways — each constituting a functional module of the cancer cell — are the units surveyed across community pathway databases. The paper characterises the landscape of cancer pathway modules represented in curated databases and how different databases differ in their module definitions and coverage."

DEFS[589] = "Modules are not explicitly defined; the paper examines the evolution of hybrid fitness during speciation. In the context of genetic incompatibility (Dobzhansky-Muller incompatibilities), co-evolved gene modules — sets of genes whose interactions within a population are compatible but whose between-population combinations are incompatible — constitute the genetic units generating hybrid incompatibility. The paper characterises how module-level epistatic incompatibilities accumulate during speciation."

DEFS[590] = "Modules are genetic circuit modules — defined gene regulatory components (logic gates, signal processing elements) assembled to program E. coli as a digital display. Each logic gate module (AND, OR, NOT) is implemented by specific genetic components and characterised by its input-output truth table. The paper demonstrates modular assembly of multiple gate modules into complex digital display circuits, with module composability enabling complex circuit function from simple characterised parts."

DEFS[591] = "Modules are genetic circuit modules — specifically, nonlinear feedback controller modules implemented using DNA strand displacement reactions. Each controller module comprises a set of DNA strand displacement reactions that implement a specific feedback control law (proportional, integral, or nonlinear). The paper characterises how these DNA-based modules can be designed to achieve desired closed-loop control properties when connected to a biological plant (target molecular system)."
